
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  Ad: 'Ad',
  AdminActivityLog: 'AdminActivityLog',
  AdminUser: 'AdminUser',
  AgencySettings: 'AgencySettings',
  Angle: 'Angle',
  ApiUsageLog: 'ApiUsageLog',
  Brand: 'Brand',
  ClientAccount: 'ClientAccount',
  ClientAdApproval: 'ClientAdApproval',
  ClientFile: 'ClientFile',
  ClientMessage: 'ClientMessage',
  ClientProject: 'ClientProject',
  JVZooTransaction: 'JVZooTransaction',
  License: 'License',
  LicenseAddon: 'LicenseAddon',
  PlatformSettings: 'PlatformSettings',
  Prompt: 'Prompt',
  UsageLog: 'UsageLog',
  User: 'User'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AdScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  imageData: 'imageData',
  imageMimeType: 'imageMimeType',
  imageMetadata: 'imageMetadata',
  headline: 'headline',
  description: 'description',
  primaryText: 'primaryText',
  callToAction: 'callToAction',
  alternativeHeadlines: 'alternativeHeadlines',
  keyBenefits: 'keyBenefits',
  toneAnalysis: 'toneAnalysis',
  productDescription: 'productDescription',
  targetAudience: 'targetAudience',
  industry: 'industry',
  category: 'category',
  template: 'template',
  tone: 'tone',
  colorPalette: 'colorPalette',
  aspectRatio: 'aspectRatio',
  valueProposition: 'valueProposition',
  angleId: 'angleId',
  copyModel: 'copyModel',
  clientAccountId: 'clientAccountId',
  projectId: 'projectId'
} as const

export type AdScalarFieldEnum = (typeof AdScalarFieldEnum)[keyof typeof AdScalarFieldEnum]


export const AdminActivityLogScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  adminUserId: 'adminUserId',
  action: 'action',
  targetType: 'targetType',
  targetId: 'targetId',
  details: 'details',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent'
} as const

export type AdminActivityLogScalarFieldEnum = (typeof AdminActivityLogScalarFieldEnum)[keyof typeof AdminActivityLogScalarFieldEnum]


export const AdminUserScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  email: 'email',
  password: 'password',
  name: 'name',
  role: 'role',
  lastLogin: 'lastLogin',
  isActive: 'isActive'
} as const

export type AdminUserScalarFieldEnum = (typeof AdminUserScalarFieldEnum)[keyof typeof AdminUserScalarFieldEnum]


export const AgencySettingsScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  agencyName: 'agencyName',
  agencyLogo: 'agencyLogo',
  logoUrl: 'logoUrl',
  primaryColor: 'primaryColor',
  secondaryColor: 'secondaryColor',
  accentColor: 'accentColor',
  customDomain: 'customDomain',
  domainVerified: 'domainVerified',
  agencyEmail: 'agencyEmail',
  agencyPhone: 'agencyPhone',
  agencyWebsite: 'agencyWebsite',
  agencyAddress: 'agencyAddress',
  portalWelcomeMessage: 'portalWelcomeMessage',
  portalFooterText: 'portalFooterText',
  showPoweredBy: 'showPoweredBy',
  emailFromName: 'emailFromName',
  emailFromEmail: 'emailFromEmail',
  emailLogoUrl: 'emailLogoUrl'
} as const

export type AgencySettingsScalarFieldEnum = (typeof AgencySettingsScalarFieldEnum)[keyof typeof AgencySettingsScalarFieldEnum]


export const AngleScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  businessName: 'businessName',
  businessDescription: 'businessDescription',
  industry: 'industry',
  targetAudience: 'targetAudience',
  currentApproach: 'currentApproach',
  angleName: 'angleName',
  angleDescription: 'angleDescription',
  whyItWorks: 'whyItWorks',
  targetEmotion: 'targetEmotion',
  exampleHeadline: 'exampleHeadline',
  visualStyle: 'visualStyle',
  copyFramework: 'copyFramework',
  metadata: 'metadata',
  usageCount: 'usageCount',
  promptsGenerated: 'promptsGenerated',
  adsGenerated: 'adsGenerated',
  performanceRating: 'performanceRating',
  performanceNotes: 'performanceNotes'
} as const

export type AngleScalarFieldEnum = (typeof AngleScalarFieldEnum)[keyof typeof AngleScalarFieldEnum]


export const ApiUsageLogScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  userId: 'userId',
  provider: 'provider',
  model: 'model',
  feature: 'feature',
  requestTokens: 'requestTokens',
  responseTokens: 'responseTokens',
  totalTokens: 'totalTokens',
  estimatedCost: 'estimatedCost',
  requestId: 'requestId',
  endpoint: 'endpoint',
  metadata: 'metadata',
  duration: 'duration',
  success: 'success'
} as const

export type ApiUsageLogScalarFieldEnum = (typeof ApiUsageLogScalarFieldEnum)[keyof typeof ApiUsageLogScalarFieldEnum]


export const BrandScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  description: 'description',
  tagline: 'tagline',
  logo: 'logo',
  logoMimeType: 'logoMimeType',
  primaryColor: 'primaryColor',
  secondaryColor: 'secondaryColor',
  accentColor: 'accentColor',
  colorPalette: 'colorPalette',
  industry: 'industry',
  targetAudience: 'targetAudience',
  brandVoice: 'brandVoice',
  tone: 'tone',
  valueProposition: 'valueProposition',
  keyMessages: 'keyMessages',
  brandGuidelines: 'brandGuidelines',
  websiteUrl: 'websiteUrl',
  socialMediaLinks: 'socialMediaLinks',
  metadata: 'metadata',
  usageCount: 'usageCount',
  lastUsed: 'lastUsed',
  userId: 'userId',
  clientAccountId: 'clientAccountId'
} as const

export type BrandScalarFieldEnum = (typeof BrandScalarFieldEnum)[keyof typeof BrandScalarFieldEnum]


export const ClientAccountScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  clientEmail: 'clientEmail',
  clientName: 'clientName',
  clientCompany: 'clientCompany',
  accessToken: 'accessToken',
  status: 'status',
  creditsAllocated: 'creditsAllocated',
  creditsUsed: 'creditsUsed',
  lastAccess: 'lastAccess',
  agencyUserId: 'agencyUserId'
} as const

export type ClientAccountScalarFieldEnum = (typeof ClientAccountScalarFieldEnum)[keyof typeof ClientAccountScalarFieldEnum]


export const ClientAdApprovalScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  adId: 'adId',
  clientAccountId: 'clientAccountId',
  status: 'status',
  feedback: 'feedback',
  requestedChanges: 'requestedChanges',
  submittedAt: 'submittedAt',
  approvedAt: 'approvedAt',
  approvedBy: 'approvedBy',
  revisionNumber: 'revisionNumber',
  previousApprovalId: 'previousApprovalId',
  submittedBy: 'submittedBy',
  submitterMessage: 'submitterMessage'
} as const

export type ClientAdApprovalScalarFieldEnum = (typeof ClientAdApprovalScalarFieldEnum)[keyof typeof ClientAdApprovalScalarFieldEnum]


export const ClientFileScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  clientAccountId: 'clientAccountId',
  fileName: 'fileName',
  fileType: 'fileType',
  mimeType: 'mimeType',
  fileUrl: 'fileUrl',
  fileSize: 'fileSize',
  thumbnailUrl: 'thumbnailUrl',
  uploadedBy: 'uploadedBy',
  uploaderType: 'uploaderType',
  uploaderName: 'uploaderName',
  description: 'description',
  tags: 'tags'
} as const

export type ClientFileScalarFieldEnum = (typeof ClientFileScalarFieldEnum)[keyof typeof ClientFileScalarFieldEnum]


export const ClientMessageScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  clientAccountId: 'clientAccountId',
  senderId: 'senderId',
  senderType: 'senderType',
  senderName: 'senderName',
  subject: 'subject',
  message: 'message',
  attachments: 'attachments',
  isRead: 'isRead',
  readAt: 'readAt',
  replyToId: 'replyToId'
} as const

export type ClientMessageScalarFieldEnum = (typeof ClientMessageScalarFieldEnum)[keyof typeof ClientMessageScalarFieldEnum]


export const ClientProjectScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  description: 'description',
  status: 'status',
  budget: 'budget',
  currency: 'currency',
  startDate: 'startDate',
  endDate: 'endDate',
  deadline: 'deadline',
  clientAccountId: 'clientAccountId',
  metadata: 'metadata'
} as const

export type ClientProjectScalarFieldEnum = (typeof ClientProjectScalarFieldEnum)[keyof typeof ClientProjectScalarFieldEnum]


export const JVZooTransactionScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  jvzooTransactionId: 'jvzooTransactionId',
  jvzooReceiptId: 'jvzooReceiptId',
  transactionType: 'transactionType',
  jvzooProductId: 'jvzooProductId',
  productType: 'productType',
  customerEmail: 'customerEmail',
  customerName: 'customerName',
  customerCountry: 'customerCountry',
  customerState: 'customerState',
  amount: 'amount',
  affiliateCommission: 'affiliateCommission',
  vendorEarnings: 'vendorEarnings',
  verificationHash: 'verificationHash',
  verified: 'verified',
  processed: 'processed',
  processedAt: 'processedAt',
  processingError: 'processingError',
  rawIpnData: 'rawIpnData',
  userId: 'userId'
} as const

export type JVZooTransactionScalarFieldEnum = (typeof JVZooTransactionScalarFieldEnum)[keyof typeof JVZooTransactionScalarFieldEnum]


export const LicenseScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  licenseKey: 'licenseKey',
  productId: 'productId',
  status: 'status',
  jvzooTransactionId: 'jvzooTransactionId',
  jvzooReceiptId: 'jvzooReceiptId',
  jvzooProductId: 'jvzooProductId',
  transactionType: 'transactionType',
  purchaseDate: 'purchaseDate',
  purchaseAmount: 'purchaseAmount',
  expiryDate: 'expiryDate',
  isRecurring: 'isRecurring',
  lastPaymentDate: 'lastPaymentDate',
  paymentCount: 'paymentCount',
  nextBillingDate: 'nextBillingDate',
  refundedAt: 'refundedAt',
  chargebackAt: 'chargebackAt',
  cancelledAt: 'cancelledAt',
  lastValidated: 'lastValidated',
  activations: 'activations',
  maxActivations: 'maxActivations',
  metadata: 'metadata',
  userId: 'userId',
  creditsResetDate: 'creditsResetDate',
  creditsTotal: 'creditsTotal',
  creditsUsed: 'creditsUsed',
  licenseTier: 'licenseTier'
} as const

export type LicenseScalarFieldEnum = (typeof LicenseScalarFieldEnum)[keyof typeof LicenseScalarFieldEnum]


export const LicenseAddonScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  addonType: 'addonType',
  status: 'status',
  jvzooProductId: 'jvzooProductId',
  jvzooTransactionId: 'jvzooTransactionId',
  jvzooReceiptId: 'jvzooReceiptId',
  purchaseDate: 'purchaseDate',
  purchaseAmount: 'purchaseAmount',
  refundedAt: 'refundedAt',
  licenseId: 'licenseId'
} as const

export type LicenseAddonScalarFieldEnum = (typeof LicenseAddonScalarFieldEnum)[keyof typeof LicenseAddonScalarFieldEnum]


export const PlatformSettingsScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  key: 'key',
  value: 'value',
  category: 'category',
  encrypted: 'encrypted',
  description: 'description',
  lastModifiedBy: 'lastModifiedBy'
} as const

export type PlatformSettingsScalarFieldEnum = (typeof PlatformSettingsScalarFieldEnum)[keyof typeof PlatformSettingsScalarFieldEnum]


export const PromptScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  idea: 'idea',
  generatedPrompt: 'generatedPrompt',
  industry: 'industry',
  style: 'style',
  aspectRatio: 'aspectRatio',
  metadata: 'metadata',
  usageCount: 'usageCount',
  angleId: 'angleId'
} as const

export type PromptScalarFieldEnum = (typeof PromptScalarFieldEnum)[keyof typeof PromptScalarFieldEnum]


export const UsageLogScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  userId: 'userId',
  licenseId: 'licenseId',
  clientAccountId: 'clientAccountId',
  actionType: 'actionType',
  creditsConsumed: 'creditsConsumed',
  aiModel: 'aiModel',
  templateId: 'templateId',
  exportFormat: 'exportFormat',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  metadata: 'metadata'
} as const

export type UsageLogScalarFieldEnum = (typeof UsageLogScalarFieldEnum)[keyof typeof UsageLogScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  email: 'email',
  company: 'company',
  geminiApiKey: 'geminiApiKey',
  openaiApiKey: 'openaiApiKey',
  preferredImageModel: 'preferredImageModel',
  imageQuality: 'imageQuality',
  defaultIndustry: 'defaultIndustry',
  defaultTone: 'defaultTone',
  defaultAspectRatio: 'defaultAspectRatio',
  adsGenerated: 'adsGenerated',
  promptsGenerated: 'promptsGenerated',
  anglesGenerated: 'anglesGenerated',
  settings: 'settings',
  defaultBrandId: 'defaultBrandId',
  theme: 'theme',
  themeMode: 'themeMode',
  emailVerified: 'emailVerified',
  password: 'password',
  resetPasswordExpires: 'resetPasswordExpires',
  resetPasswordToken: 'resetPasswordToken',
  verificationToken: 'verificationToken',
  defaultModel: 'defaultModel',
  createdVia: 'createdVia',
  jvzooCustomerId: 'jvzooCustomerId',
  jvzooTransactionId: 'jvzooTransactionId'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

