
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Ad
 * 
 */
export type Ad = Prisma.AdModel
/**
 * Model AdminActivityLog
 * 
 */
export type AdminActivityLog = Prisma.AdminActivityLogModel
/**
 * Model AdminUser
 * 
 */
export type AdminUser = Prisma.AdminUserModel
/**
 * Model AgencySettings
 * 
 */
export type AgencySettings = Prisma.AgencySettingsModel
/**
 * Model Angle
 * 
 */
export type Angle = Prisma.AngleModel
/**
 * Model ApiUsageLog
 * 
 */
export type ApiUsageLog = Prisma.ApiUsageLogModel
/**
 * Model Brand
 * 
 */
export type Brand = Prisma.BrandModel
/**
 * Model ClientAccount
 * 
 */
export type ClientAccount = Prisma.ClientAccountModel
/**
 * Model ClientAdApproval
 * 
 */
export type ClientAdApproval = Prisma.ClientAdApprovalModel
/**
 * Model ClientFile
 * 
 */
export type ClientFile = Prisma.ClientFileModel
/**
 * Model ClientMessage
 * 
 */
export type ClientMessage = Prisma.ClientMessageModel
/**
 * Model ClientProject
 * 
 */
export type ClientProject = Prisma.ClientProjectModel
/**
 * Model JVZooTransaction
 * 
 */
export type JVZooTransaction = Prisma.JVZooTransactionModel
/**
 * Model License
 * 
 */
export type License = Prisma.LicenseModel
/**
 * Model LicenseAddon
 * 
 */
export type LicenseAddon = Prisma.LicenseAddonModel
/**
 * Model PlatformSettings
 * 
 */
export type PlatformSettings = Prisma.PlatformSettingsModel
/**
 * Model Prompt
 * 
 */
export type Prompt = Prisma.PromptModel
/**
 * Model UsageLog
 * 
 */
export type UsageLog = Prisma.UsageLogModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
