
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AgencySettings` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AgencySettings
 * 
 */
export type AgencySettingsModel = runtime.Types.Result.DefaultSelection<Prisma.$AgencySettingsPayload>

export type AggregateAgencySettings = {
  _count: AgencySettingsCountAggregateOutputType | null
  _min: AgencySettingsMinAggregateOutputType | null
  _max: AgencySettingsMaxAggregateOutputType | null
}

export type AgencySettingsMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  agencyName: string | null
  agencyLogo: string | null
  logoUrl: string | null
  primaryColor: string | null
  secondaryColor: string | null
  accentColor: string | null
  customDomain: string | null
  domainVerified: boolean | null
  agencyEmail: string | null
  agencyPhone: string | null
  agencyWebsite: string | null
  agencyAddress: string | null
  portalWelcomeMessage: string | null
  portalFooterText: string | null
  showPoweredBy: boolean | null
  emailFromName: string | null
  emailFromEmail: string | null
  emailLogoUrl: string | null
}

export type AgencySettingsMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  agencyName: string | null
  agencyLogo: string | null
  logoUrl: string | null
  primaryColor: string | null
  secondaryColor: string | null
  accentColor: string | null
  customDomain: string | null
  domainVerified: boolean | null
  agencyEmail: string | null
  agencyPhone: string | null
  agencyWebsite: string | null
  agencyAddress: string | null
  portalWelcomeMessage: string | null
  portalFooterText: string | null
  showPoweredBy: boolean | null
  emailFromName: string | null
  emailFromEmail: string | null
  emailLogoUrl: string | null
}

export type AgencySettingsCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  userId: number
  agencyName: number
  agencyLogo: number
  logoUrl: number
  primaryColor: number
  secondaryColor: number
  accentColor: number
  customDomain: number
  domainVerified: number
  agencyEmail: number
  agencyPhone: number
  agencyWebsite: number
  agencyAddress: number
  portalWelcomeMessage: number
  portalFooterText: number
  showPoweredBy: number
  emailFromName: number
  emailFromEmail: number
  emailLogoUrl: number
  _all: number
}


export type AgencySettingsMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  agencyName?: true
  agencyLogo?: true
  logoUrl?: true
  primaryColor?: true
  secondaryColor?: true
  accentColor?: true
  customDomain?: true
  domainVerified?: true
  agencyEmail?: true
  agencyPhone?: true
  agencyWebsite?: true
  agencyAddress?: true
  portalWelcomeMessage?: true
  portalFooterText?: true
  showPoweredBy?: true
  emailFromName?: true
  emailFromEmail?: true
  emailLogoUrl?: true
}

export type AgencySettingsMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  agencyName?: true
  agencyLogo?: true
  logoUrl?: true
  primaryColor?: true
  secondaryColor?: true
  accentColor?: true
  customDomain?: true
  domainVerified?: true
  agencyEmail?: true
  agencyPhone?: true
  agencyWebsite?: true
  agencyAddress?: true
  portalWelcomeMessage?: true
  portalFooterText?: true
  showPoweredBy?: true
  emailFromName?: true
  emailFromEmail?: true
  emailLogoUrl?: true
}

export type AgencySettingsCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  agencyName?: true
  agencyLogo?: true
  logoUrl?: true
  primaryColor?: true
  secondaryColor?: true
  accentColor?: true
  customDomain?: true
  domainVerified?: true
  agencyEmail?: true
  agencyPhone?: true
  agencyWebsite?: true
  agencyAddress?: true
  portalWelcomeMessage?: true
  portalFooterText?: true
  showPoweredBy?: true
  emailFromName?: true
  emailFromEmail?: true
  emailLogoUrl?: true
  _all?: true
}

export type AgencySettingsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgencySettings to aggregate.
   */
  where?: Prisma.AgencySettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgencySettings to fetch.
   */
  orderBy?: Prisma.AgencySettingsOrderByWithRelationInput | Prisma.AgencySettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgencySettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgencySettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgencySettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AgencySettings
  **/
  _count?: true | AgencySettingsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgencySettingsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgencySettingsMaxAggregateInputType
}

export type GetAgencySettingsAggregateType<T extends AgencySettingsAggregateArgs> = {
      [P in keyof T & keyof AggregateAgencySettings]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgencySettings[P]>
    : Prisma.GetScalarType<T[P], AggregateAgencySettings[P]>
}




export type AgencySettingsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgencySettingsWhereInput
  orderBy?: Prisma.AgencySettingsOrderByWithAggregationInput | Prisma.AgencySettingsOrderByWithAggregationInput[]
  by: Prisma.AgencySettingsScalarFieldEnum[] | Prisma.AgencySettingsScalarFieldEnum
  having?: Prisma.AgencySettingsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgencySettingsCountAggregateInputType | true
  _min?: AgencySettingsMinAggregateInputType
  _max?: AgencySettingsMaxAggregateInputType
}

export type AgencySettingsGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  userId: string
  agencyName: string | null
  agencyLogo: string | null
  logoUrl: string | null
  primaryColor: string
  secondaryColor: string
  accentColor: string | null
  customDomain: string | null
  domainVerified: boolean
  agencyEmail: string | null
  agencyPhone: string | null
  agencyWebsite: string | null
  agencyAddress: string | null
  portalWelcomeMessage: string | null
  portalFooterText: string | null
  showPoweredBy: boolean
  emailFromName: string | null
  emailFromEmail: string | null
  emailLogoUrl: string | null
  _count: AgencySettingsCountAggregateOutputType | null
  _min: AgencySettingsMinAggregateOutputType | null
  _max: AgencySettingsMaxAggregateOutputType | null
}

type GetAgencySettingsGroupByPayload<T extends AgencySettingsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgencySettingsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgencySettingsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgencySettingsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgencySettingsGroupByOutputType[P]>
      }
    >
  >



export type AgencySettingsWhereInput = {
  AND?: Prisma.AgencySettingsWhereInput | Prisma.AgencySettingsWhereInput[]
  OR?: Prisma.AgencySettingsWhereInput[]
  NOT?: Prisma.AgencySettingsWhereInput | Prisma.AgencySettingsWhereInput[]
  id?: Prisma.StringFilter<"AgencySettings"> | string
  createdAt?: Prisma.DateTimeFilter<"AgencySettings"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AgencySettings"> | Date | string
  userId?: Prisma.StringFilter<"AgencySettings"> | string
  agencyName?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  agencyLogo?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  logoUrl?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  primaryColor?: Prisma.StringFilter<"AgencySettings"> | string
  secondaryColor?: Prisma.StringFilter<"AgencySettings"> | string
  accentColor?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  customDomain?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  domainVerified?: Prisma.BoolFilter<"AgencySettings"> | boolean
  agencyEmail?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  agencyPhone?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  agencyWebsite?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  agencyAddress?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  portalWelcomeMessage?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  portalFooterText?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  showPoweredBy?: Prisma.BoolFilter<"AgencySettings"> | boolean
  emailFromName?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  emailFromEmail?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  emailLogoUrl?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type AgencySettingsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  agencyName?: Prisma.SortOrderInput | Prisma.SortOrder
  agencyLogo?: Prisma.SortOrderInput | Prisma.SortOrder
  logoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  primaryColor?: Prisma.SortOrder
  secondaryColor?: Prisma.SortOrder
  accentColor?: Prisma.SortOrderInput | Prisma.SortOrder
  customDomain?: Prisma.SortOrderInput | Prisma.SortOrder
  domainVerified?: Prisma.SortOrder
  agencyEmail?: Prisma.SortOrderInput | Prisma.SortOrder
  agencyPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  agencyWebsite?: Prisma.SortOrderInput | Prisma.SortOrder
  agencyAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  portalWelcomeMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  portalFooterText?: Prisma.SortOrderInput | Prisma.SortOrder
  showPoweredBy?: Prisma.SortOrder
  emailFromName?: Prisma.SortOrderInput | Prisma.SortOrder
  emailFromEmail?: Prisma.SortOrderInput | Prisma.SortOrder
  emailLogoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  User?: Prisma.UserOrderByWithRelationInput
}

export type AgencySettingsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.AgencySettingsWhereInput | Prisma.AgencySettingsWhereInput[]
  OR?: Prisma.AgencySettingsWhereInput[]
  NOT?: Prisma.AgencySettingsWhereInput | Prisma.AgencySettingsWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"AgencySettings"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AgencySettings"> | Date | string
  agencyName?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  agencyLogo?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  logoUrl?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  primaryColor?: Prisma.StringFilter<"AgencySettings"> | string
  secondaryColor?: Prisma.StringFilter<"AgencySettings"> | string
  accentColor?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  customDomain?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  domainVerified?: Prisma.BoolFilter<"AgencySettings"> | boolean
  agencyEmail?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  agencyPhone?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  agencyWebsite?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  agencyAddress?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  portalWelcomeMessage?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  portalFooterText?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  showPoweredBy?: Prisma.BoolFilter<"AgencySettings"> | boolean
  emailFromName?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  emailFromEmail?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  emailLogoUrl?: Prisma.StringNullableFilter<"AgencySettings"> | string | null
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId">

export type AgencySettingsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  agencyName?: Prisma.SortOrderInput | Prisma.SortOrder
  agencyLogo?: Prisma.SortOrderInput | Prisma.SortOrder
  logoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  primaryColor?: Prisma.SortOrder
  secondaryColor?: Prisma.SortOrder
  accentColor?: Prisma.SortOrderInput | Prisma.SortOrder
  customDomain?: Prisma.SortOrderInput | Prisma.SortOrder
  domainVerified?: Prisma.SortOrder
  agencyEmail?: Prisma.SortOrderInput | Prisma.SortOrder
  agencyPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  agencyWebsite?: Prisma.SortOrderInput | Prisma.SortOrder
  agencyAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  portalWelcomeMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  portalFooterText?: Prisma.SortOrderInput | Prisma.SortOrder
  showPoweredBy?: Prisma.SortOrder
  emailFromName?: Prisma.SortOrderInput | Prisma.SortOrder
  emailFromEmail?: Prisma.SortOrderInput | Prisma.SortOrder
  emailLogoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AgencySettingsCountOrderByAggregateInput
  _max?: Prisma.AgencySettingsMaxOrderByAggregateInput
  _min?: Prisma.AgencySettingsMinOrderByAggregateInput
}

export type AgencySettingsScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgencySettingsScalarWhereWithAggregatesInput | Prisma.AgencySettingsScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgencySettingsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgencySettingsScalarWhereWithAggregatesInput | Prisma.AgencySettingsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AgencySettings"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AgencySettings"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AgencySettings"> | Date | string
  userId?: Prisma.StringWithAggregatesFilter<"AgencySettings"> | string
  agencyName?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
  agencyLogo?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
  logoUrl?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
  primaryColor?: Prisma.StringWithAggregatesFilter<"AgencySettings"> | string
  secondaryColor?: Prisma.StringWithAggregatesFilter<"AgencySettings"> | string
  accentColor?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
  customDomain?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
  domainVerified?: Prisma.BoolWithAggregatesFilter<"AgencySettings"> | boolean
  agencyEmail?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
  agencyPhone?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
  agencyWebsite?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
  agencyAddress?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
  portalWelcomeMessage?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
  portalFooterText?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
  showPoweredBy?: Prisma.BoolWithAggregatesFilter<"AgencySettings"> | boolean
  emailFromName?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
  emailFromEmail?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
  emailLogoUrl?: Prisma.StringNullableWithAggregatesFilter<"AgencySettings"> | string | null
}

export type AgencySettingsCreateInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  agencyName?: string | null
  agencyLogo?: string | null
  logoUrl?: string | null
  primaryColor?: string
  secondaryColor?: string
  accentColor?: string | null
  customDomain?: string | null
  domainVerified?: boolean
  agencyEmail?: string | null
  agencyPhone?: string | null
  agencyWebsite?: string | null
  agencyAddress?: string | null
  portalWelcomeMessage?: string | null
  portalFooterText?: string | null
  showPoweredBy?: boolean
  emailFromName?: string | null
  emailFromEmail?: string | null
  emailLogoUrl?: string | null
  User: Prisma.UserCreateNestedOneWithoutAgencySettingsInput
}

export type AgencySettingsUncheckedCreateInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  userId: string
  agencyName?: string | null
  agencyLogo?: string | null
  logoUrl?: string | null
  primaryColor?: string
  secondaryColor?: string
  accentColor?: string | null
  customDomain?: string | null
  domainVerified?: boolean
  agencyEmail?: string | null
  agencyPhone?: string | null
  agencyWebsite?: string | null
  agencyAddress?: string | null
  portalWelcomeMessage?: string | null
  portalFooterText?: string | null
  showPoweredBy?: boolean
  emailFromName?: string | null
  emailFromEmail?: string | null
  emailLogoUrl?: string | null
}

export type AgencySettingsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agencyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyLogo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryColor?: Prisma.StringFieldUpdateOperationsInput | string
  secondaryColor?: Prisma.StringFieldUpdateOperationsInput | string
  accentColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customDomain?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  domainVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  agencyEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portalWelcomeMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portalFooterText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  showPoweredBy?: Prisma.BoolFieldUpdateOperationsInput | boolean
  emailFromName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailFromEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailLogoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  User?: Prisma.UserUpdateOneRequiredWithoutAgencySettingsNestedInput
}

export type AgencySettingsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  agencyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyLogo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryColor?: Prisma.StringFieldUpdateOperationsInput | string
  secondaryColor?: Prisma.StringFieldUpdateOperationsInput | string
  accentColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customDomain?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  domainVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  agencyEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portalWelcomeMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portalFooterText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  showPoweredBy?: Prisma.BoolFieldUpdateOperationsInput | boolean
  emailFromName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailFromEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailLogoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AgencySettingsCreateManyInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  userId: string
  agencyName?: string | null
  agencyLogo?: string | null
  logoUrl?: string | null
  primaryColor?: string
  secondaryColor?: string
  accentColor?: string | null
  customDomain?: string | null
  domainVerified?: boolean
  agencyEmail?: string | null
  agencyPhone?: string | null
  agencyWebsite?: string | null
  agencyAddress?: string | null
  portalWelcomeMessage?: string | null
  portalFooterText?: string | null
  showPoweredBy?: boolean
  emailFromName?: string | null
  emailFromEmail?: string | null
  emailLogoUrl?: string | null
}

export type AgencySettingsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agencyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyLogo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryColor?: Prisma.StringFieldUpdateOperationsInput | string
  secondaryColor?: Prisma.StringFieldUpdateOperationsInput | string
  accentColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customDomain?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  domainVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  agencyEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portalWelcomeMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portalFooterText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  showPoweredBy?: Prisma.BoolFieldUpdateOperationsInput | boolean
  emailFromName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailFromEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailLogoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AgencySettingsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  agencyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyLogo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryColor?: Prisma.StringFieldUpdateOperationsInput | string
  secondaryColor?: Prisma.StringFieldUpdateOperationsInput | string
  accentColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customDomain?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  domainVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  agencyEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portalWelcomeMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portalFooterText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  showPoweredBy?: Prisma.BoolFieldUpdateOperationsInput | boolean
  emailFromName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailFromEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailLogoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AgencySettingsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  agencyName?: Prisma.SortOrder
  agencyLogo?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  primaryColor?: Prisma.SortOrder
  secondaryColor?: Prisma.SortOrder
  accentColor?: Prisma.SortOrder
  customDomain?: Prisma.SortOrder
  domainVerified?: Prisma.SortOrder
  agencyEmail?: Prisma.SortOrder
  agencyPhone?: Prisma.SortOrder
  agencyWebsite?: Prisma.SortOrder
  agencyAddress?: Prisma.SortOrder
  portalWelcomeMessage?: Prisma.SortOrder
  portalFooterText?: Prisma.SortOrder
  showPoweredBy?: Prisma.SortOrder
  emailFromName?: Prisma.SortOrder
  emailFromEmail?: Prisma.SortOrder
  emailLogoUrl?: Prisma.SortOrder
}

export type AgencySettingsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  agencyName?: Prisma.SortOrder
  agencyLogo?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  primaryColor?: Prisma.SortOrder
  secondaryColor?: Prisma.SortOrder
  accentColor?: Prisma.SortOrder
  customDomain?: Prisma.SortOrder
  domainVerified?: Prisma.SortOrder
  agencyEmail?: Prisma.SortOrder
  agencyPhone?: Prisma.SortOrder
  agencyWebsite?: Prisma.SortOrder
  agencyAddress?: Prisma.SortOrder
  portalWelcomeMessage?: Prisma.SortOrder
  portalFooterText?: Prisma.SortOrder
  showPoweredBy?: Prisma.SortOrder
  emailFromName?: Prisma.SortOrder
  emailFromEmail?: Prisma.SortOrder
  emailLogoUrl?: Prisma.SortOrder
}

export type AgencySettingsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  agencyName?: Prisma.SortOrder
  agencyLogo?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  primaryColor?: Prisma.SortOrder
  secondaryColor?: Prisma.SortOrder
  accentColor?: Prisma.SortOrder
  customDomain?: Prisma.SortOrder
  domainVerified?: Prisma.SortOrder
  agencyEmail?: Prisma.SortOrder
  agencyPhone?: Prisma.SortOrder
  agencyWebsite?: Prisma.SortOrder
  agencyAddress?: Prisma.SortOrder
  portalWelcomeMessage?: Prisma.SortOrder
  portalFooterText?: Prisma.SortOrder
  showPoweredBy?: Prisma.SortOrder
  emailFromName?: Prisma.SortOrder
  emailFromEmail?: Prisma.SortOrder
  emailLogoUrl?: Prisma.SortOrder
}

export type AgencySettingsNullableScalarRelationFilter = {
  is?: Prisma.AgencySettingsWhereInput | null
  isNot?: Prisma.AgencySettingsWhereInput | null
}

export type AgencySettingsCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AgencySettingsCreateWithoutUserInput, Prisma.AgencySettingsUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AgencySettingsCreateOrConnectWithoutUserInput
  connect?: Prisma.AgencySettingsWhereUniqueInput
}

export type AgencySettingsUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AgencySettingsCreateWithoutUserInput, Prisma.AgencySettingsUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AgencySettingsCreateOrConnectWithoutUserInput
  connect?: Prisma.AgencySettingsWhereUniqueInput
}

export type AgencySettingsUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AgencySettingsCreateWithoutUserInput, Prisma.AgencySettingsUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AgencySettingsCreateOrConnectWithoutUserInput
  upsert?: Prisma.AgencySettingsUpsertWithoutUserInput
  disconnect?: Prisma.AgencySettingsWhereInput | boolean
  delete?: Prisma.AgencySettingsWhereInput | boolean
  connect?: Prisma.AgencySettingsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgencySettingsUpdateToOneWithWhereWithoutUserInput, Prisma.AgencySettingsUpdateWithoutUserInput>, Prisma.AgencySettingsUncheckedUpdateWithoutUserInput>
}

export type AgencySettingsUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AgencySettingsCreateWithoutUserInput, Prisma.AgencySettingsUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AgencySettingsCreateOrConnectWithoutUserInput
  upsert?: Prisma.AgencySettingsUpsertWithoutUserInput
  disconnect?: Prisma.AgencySettingsWhereInput | boolean
  delete?: Prisma.AgencySettingsWhereInput | boolean
  connect?: Prisma.AgencySettingsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgencySettingsUpdateToOneWithWhereWithoutUserInput, Prisma.AgencySettingsUpdateWithoutUserInput>, Prisma.AgencySettingsUncheckedUpdateWithoutUserInput>
}

export type AgencySettingsCreateWithoutUserInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  agencyName?: string | null
  agencyLogo?: string | null
  logoUrl?: string | null
  primaryColor?: string
  secondaryColor?: string
  accentColor?: string | null
  customDomain?: string | null
  domainVerified?: boolean
  agencyEmail?: string | null
  agencyPhone?: string | null
  agencyWebsite?: string | null
  agencyAddress?: string | null
  portalWelcomeMessage?: string | null
  portalFooterText?: string | null
  showPoweredBy?: boolean
  emailFromName?: string | null
  emailFromEmail?: string | null
  emailLogoUrl?: string | null
}

export type AgencySettingsUncheckedCreateWithoutUserInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  agencyName?: string | null
  agencyLogo?: string | null
  logoUrl?: string | null
  primaryColor?: string
  secondaryColor?: string
  accentColor?: string | null
  customDomain?: string | null
  domainVerified?: boolean
  agencyEmail?: string | null
  agencyPhone?: string | null
  agencyWebsite?: string | null
  agencyAddress?: string | null
  portalWelcomeMessage?: string | null
  portalFooterText?: string | null
  showPoweredBy?: boolean
  emailFromName?: string | null
  emailFromEmail?: string | null
  emailLogoUrl?: string | null
}

export type AgencySettingsCreateOrConnectWithoutUserInput = {
  where: Prisma.AgencySettingsWhereUniqueInput
  create: Prisma.XOR<Prisma.AgencySettingsCreateWithoutUserInput, Prisma.AgencySettingsUncheckedCreateWithoutUserInput>
}

export type AgencySettingsUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.AgencySettingsUpdateWithoutUserInput, Prisma.AgencySettingsUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AgencySettingsCreateWithoutUserInput, Prisma.AgencySettingsUncheckedCreateWithoutUserInput>
  where?: Prisma.AgencySettingsWhereInput
}

export type AgencySettingsUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.AgencySettingsWhereInput
  data: Prisma.XOR<Prisma.AgencySettingsUpdateWithoutUserInput, Prisma.AgencySettingsUncheckedUpdateWithoutUserInput>
}

export type AgencySettingsUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agencyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyLogo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryColor?: Prisma.StringFieldUpdateOperationsInput | string
  secondaryColor?: Prisma.StringFieldUpdateOperationsInput | string
  accentColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customDomain?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  domainVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  agencyEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portalWelcomeMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portalFooterText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  showPoweredBy?: Prisma.BoolFieldUpdateOperationsInput | boolean
  emailFromName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailFromEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailLogoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AgencySettingsUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agencyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyLogo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryColor?: Prisma.StringFieldUpdateOperationsInput | string
  secondaryColor?: Prisma.StringFieldUpdateOperationsInput | string
  accentColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customDomain?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  domainVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  agencyEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  agencyAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portalWelcomeMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  portalFooterText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  showPoweredBy?: Prisma.BoolFieldUpdateOperationsInput | boolean
  emailFromName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailFromEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailLogoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type AgencySettingsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  agencyName?: boolean
  agencyLogo?: boolean
  logoUrl?: boolean
  primaryColor?: boolean
  secondaryColor?: boolean
  accentColor?: boolean
  customDomain?: boolean
  domainVerified?: boolean
  agencyEmail?: boolean
  agencyPhone?: boolean
  agencyWebsite?: boolean
  agencyAddress?: boolean
  portalWelcomeMessage?: boolean
  portalFooterText?: boolean
  showPoweredBy?: boolean
  emailFromName?: boolean
  emailFromEmail?: boolean
  emailLogoUrl?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agencySettings"]>

export type AgencySettingsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  agencyName?: boolean
  agencyLogo?: boolean
  logoUrl?: boolean
  primaryColor?: boolean
  secondaryColor?: boolean
  accentColor?: boolean
  customDomain?: boolean
  domainVerified?: boolean
  agencyEmail?: boolean
  agencyPhone?: boolean
  agencyWebsite?: boolean
  agencyAddress?: boolean
  portalWelcomeMessage?: boolean
  portalFooterText?: boolean
  showPoweredBy?: boolean
  emailFromName?: boolean
  emailFromEmail?: boolean
  emailLogoUrl?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agencySettings"]>

export type AgencySettingsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  agencyName?: boolean
  agencyLogo?: boolean
  logoUrl?: boolean
  primaryColor?: boolean
  secondaryColor?: boolean
  accentColor?: boolean
  customDomain?: boolean
  domainVerified?: boolean
  agencyEmail?: boolean
  agencyPhone?: boolean
  agencyWebsite?: boolean
  agencyAddress?: boolean
  portalWelcomeMessage?: boolean
  portalFooterText?: boolean
  showPoweredBy?: boolean
  emailFromName?: boolean
  emailFromEmail?: boolean
  emailLogoUrl?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agencySettings"]>

export type AgencySettingsSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  agencyName?: boolean
  agencyLogo?: boolean
  logoUrl?: boolean
  primaryColor?: boolean
  secondaryColor?: boolean
  accentColor?: boolean
  customDomain?: boolean
  domainVerified?: boolean
  agencyEmail?: boolean
  agencyPhone?: boolean
  agencyWebsite?: boolean
  agencyAddress?: boolean
  portalWelcomeMessage?: boolean
  portalFooterText?: boolean
  showPoweredBy?: boolean
  emailFromName?: boolean
  emailFromEmail?: boolean
  emailLogoUrl?: boolean
}

export type AgencySettingsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "userId" | "agencyName" | "agencyLogo" | "logoUrl" | "primaryColor" | "secondaryColor" | "accentColor" | "customDomain" | "domainVerified" | "agencyEmail" | "agencyPhone" | "agencyWebsite" | "agencyAddress" | "portalWelcomeMessage" | "portalFooterText" | "showPoweredBy" | "emailFromName" | "emailFromEmail" | "emailLogoUrl", ExtArgs["result"]["agencySettings"]>
export type AgencySettingsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AgencySettingsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AgencySettingsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AgencySettingsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AgencySettings"
  objects: {
    User: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    userId: string
    agencyName: string | null
    agencyLogo: string | null
    logoUrl: string | null
    primaryColor: string
    secondaryColor: string
    accentColor: string | null
    customDomain: string | null
    domainVerified: boolean
    agencyEmail: string | null
    agencyPhone: string | null
    agencyWebsite: string | null
    agencyAddress: string | null
    portalWelcomeMessage: string | null
    portalFooterText: string | null
    showPoweredBy: boolean
    emailFromName: string | null
    emailFromEmail: string | null
    emailLogoUrl: string | null
  }, ExtArgs["result"]["agencySettings"]>
  composites: {}
}

export type AgencySettingsGetPayload<S extends boolean | null | undefined | AgencySettingsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgencySettingsPayload, S>

export type AgencySettingsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgencySettingsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgencySettingsCountAggregateInputType | true
  }

export interface AgencySettingsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AgencySettings'], meta: { name: 'AgencySettings' } }
  /**
   * Find zero or one AgencySettings that matches the filter.
   * @param {AgencySettingsFindUniqueArgs} args - Arguments to find a AgencySettings
   * @example
   * // Get one AgencySettings
   * const agencySettings = await prisma.agencySettings.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgencySettingsFindUniqueArgs>(args: Prisma.SelectSubset<T, AgencySettingsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgencySettingsClient<runtime.Types.Result.GetResult<Prisma.$AgencySettingsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AgencySettings that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgencySettingsFindUniqueOrThrowArgs} args - Arguments to find a AgencySettings
   * @example
   * // Get one AgencySettings
   * const agencySettings = await prisma.agencySettings.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgencySettingsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgencySettingsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgencySettingsClient<runtime.Types.Result.GetResult<Prisma.$AgencySettingsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgencySettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencySettingsFindFirstArgs} args - Arguments to find a AgencySettings
   * @example
   * // Get one AgencySettings
   * const agencySettings = await prisma.agencySettings.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgencySettingsFindFirstArgs>(args?: Prisma.SelectSubset<T, AgencySettingsFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgencySettingsClient<runtime.Types.Result.GetResult<Prisma.$AgencySettingsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgencySettings that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencySettingsFindFirstOrThrowArgs} args - Arguments to find a AgencySettings
   * @example
   * // Get one AgencySettings
   * const agencySettings = await prisma.agencySettings.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgencySettingsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgencySettingsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgencySettingsClient<runtime.Types.Result.GetResult<Prisma.$AgencySettingsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AgencySettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencySettingsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AgencySettings
   * const agencySettings = await prisma.agencySettings.findMany()
   * 
   * // Get first 10 AgencySettings
   * const agencySettings = await prisma.agencySettings.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const agencySettingsWithIdOnly = await prisma.agencySettings.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AgencySettingsFindManyArgs>(args?: Prisma.SelectSubset<T, AgencySettingsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencySettingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AgencySettings.
   * @param {AgencySettingsCreateArgs} args - Arguments to create a AgencySettings.
   * @example
   * // Create one AgencySettings
   * const AgencySettings = await prisma.agencySettings.create({
   *   data: {
   *     // ... data to create a AgencySettings
   *   }
   * })
   * 
   */
  create<T extends AgencySettingsCreateArgs>(args: Prisma.SelectSubset<T, AgencySettingsCreateArgs<ExtArgs>>): Prisma.Prisma__AgencySettingsClient<runtime.Types.Result.GetResult<Prisma.$AgencySettingsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AgencySettings.
   * @param {AgencySettingsCreateManyArgs} args - Arguments to create many AgencySettings.
   * @example
   * // Create many AgencySettings
   * const agencySettings = await prisma.agencySettings.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgencySettingsCreateManyArgs>(args?: Prisma.SelectSubset<T, AgencySettingsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AgencySettings and returns the data saved in the database.
   * @param {AgencySettingsCreateManyAndReturnArgs} args - Arguments to create many AgencySettings.
   * @example
   * // Create many AgencySettings
   * const agencySettings = await prisma.agencySettings.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AgencySettings and only return the `id`
   * const agencySettingsWithIdOnly = await prisma.agencySettings.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AgencySettingsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AgencySettingsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencySettingsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AgencySettings.
   * @param {AgencySettingsDeleteArgs} args - Arguments to delete one AgencySettings.
   * @example
   * // Delete one AgencySettings
   * const AgencySettings = await prisma.agencySettings.delete({
   *   where: {
   *     // ... filter to delete one AgencySettings
   *   }
   * })
   * 
   */
  delete<T extends AgencySettingsDeleteArgs>(args: Prisma.SelectSubset<T, AgencySettingsDeleteArgs<ExtArgs>>): Prisma.Prisma__AgencySettingsClient<runtime.Types.Result.GetResult<Prisma.$AgencySettingsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AgencySettings.
   * @param {AgencySettingsUpdateArgs} args - Arguments to update one AgencySettings.
   * @example
   * // Update one AgencySettings
   * const agencySettings = await prisma.agencySettings.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgencySettingsUpdateArgs>(args: Prisma.SelectSubset<T, AgencySettingsUpdateArgs<ExtArgs>>): Prisma.Prisma__AgencySettingsClient<runtime.Types.Result.GetResult<Prisma.$AgencySettingsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AgencySettings.
   * @param {AgencySettingsDeleteManyArgs} args - Arguments to filter AgencySettings to delete.
   * @example
   * // Delete a few AgencySettings
   * const { count } = await prisma.agencySettings.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgencySettingsDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgencySettingsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgencySettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencySettingsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AgencySettings
   * const agencySettings = await prisma.agencySettings.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgencySettingsUpdateManyArgs>(args: Prisma.SelectSubset<T, AgencySettingsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgencySettings and returns the data updated in the database.
   * @param {AgencySettingsUpdateManyAndReturnArgs} args - Arguments to update many AgencySettings.
   * @example
   * // Update many AgencySettings
   * const agencySettings = await prisma.agencySettings.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AgencySettings and only return the `id`
   * const agencySettingsWithIdOnly = await prisma.agencySettings.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AgencySettingsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AgencySettingsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencySettingsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AgencySettings.
   * @param {AgencySettingsUpsertArgs} args - Arguments to update or create a AgencySettings.
   * @example
   * // Update or create a AgencySettings
   * const agencySettings = await prisma.agencySettings.upsert({
   *   create: {
   *     // ... data to create a AgencySettings
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AgencySettings we want to update
   *   }
   * })
   */
  upsert<T extends AgencySettingsUpsertArgs>(args: Prisma.SelectSubset<T, AgencySettingsUpsertArgs<ExtArgs>>): Prisma.Prisma__AgencySettingsClient<runtime.Types.Result.GetResult<Prisma.$AgencySettingsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AgencySettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencySettingsCountArgs} args - Arguments to filter AgencySettings to count.
   * @example
   * // Count the number of AgencySettings
   * const count = await prisma.agencySettings.count({
   *   where: {
   *     // ... the filter for the AgencySettings we want to count
   *   }
   * })
  **/
  count<T extends AgencySettingsCountArgs>(
    args?: Prisma.Subset<T, AgencySettingsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgencySettingsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AgencySettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencySettingsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgencySettingsAggregateArgs>(args: Prisma.Subset<T, AgencySettingsAggregateArgs>): Prisma.PrismaPromise<GetAgencySettingsAggregateType<T>>

  /**
   * Group by AgencySettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencySettingsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgencySettingsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgencySettingsGroupByArgs['orderBy'] }
      : { orderBy?: AgencySettingsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgencySettingsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgencySettingsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AgencySettings model
 */
readonly fields: AgencySettingsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AgencySettings.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgencySettingsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  User<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AgencySettings model
 */
export interface AgencySettingsFieldRefs {
  readonly id: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly createdAt: Prisma.FieldRef<"AgencySettings", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AgencySettings", 'DateTime'>
  readonly userId: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly agencyName: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly agencyLogo: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly logoUrl: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly primaryColor: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly secondaryColor: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly accentColor: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly customDomain: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly domainVerified: Prisma.FieldRef<"AgencySettings", 'Boolean'>
  readonly agencyEmail: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly agencyPhone: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly agencyWebsite: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly agencyAddress: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly portalWelcomeMessage: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly portalFooterText: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly showPoweredBy: Prisma.FieldRef<"AgencySettings", 'Boolean'>
  readonly emailFromName: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly emailFromEmail: Prisma.FieldRef<"AgencySettings", 'String'>
  readonly emailLogoUrl: Prisma.FieldRef<"AgencySettings", 'String'>
}
    

// Custom InputTypes
/**
 * AgencySettings findUnique
 */
export type AgencySettingsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencySettings
   */
  select?: Prisma.AgencySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencySettings
   */
  omit?: Prisma.AgencySettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencySettingsInclude<ExtArgs> | null
  /**
   * Filter, which AgencySettings to fetch.
   */
  where: Prisma.AgencySettingsWhereUniqueInput
}

/**
 * AgencySettings findUniqueOrThrow
 */
export type AgencySettingsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencySettings
   */
  select?: Prisma.AgencySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencySettings
   */
  omit?: Prisma.AgencySettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencySettingsInclude<ExtArgs> | null
  /**
   * Filter, which AgencySettings to fetch.
   */
  where: Prisma.AgencySettingsWhereUniqueInput
}

/**
 * AgencySettings findFirst
 */
export type AgencySettingsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencySettings
   */
  select?: Prisma.AgencySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencySettings
   */
  omit?: Prisma.AgencySettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencySettingsInclude<ExtArgs> | null
  /**
   * Filter, which AgencySettings to fetch.
   */
  where?: Prisma.AgencySettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgencySettings to fetch.
   */
  orderBy?: Prisma.AgencySettingsOrderByWithRelationInput | Prisma.AgencySettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgencySettings.
   */
  cursor?: Prisma.AgencySettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgencySettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgencySettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgencySettings.
   */
  distinct?: Prisma.AgencySettingsScalarFieldEnum | Prisma.AgencySettingsScalarFieldEnum[]
}

/**
 * AgencySettings findFirstOrThrow
 */
export type AgencySettingsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencySettings
   */
  select?: Prisma.AgencySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencySettings
   */
  omit?: Prisma.AgencySettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencySettingsInclude<ExtArgs> | null
  /**
   * Filter, which AgencySettings to fetch.
   */
  where?: Prisma.AgencySettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgencySettings to fetch.
   */
  orderBy?: Prisma.AgencySettingsOrderByWithRelationInput | Prisma.AgencySettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgencySettings.
   */
  cursor?: Prisma.AgencySettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgencySettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgencySettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgencySettings.
   */
  distinct?: Prisma.AgencySettingsScalarFieldEnum | Prisma.AgencySettingsScalarFieldEnum[]
}

/**
 * AgencySettings findMany
 */
export type AgencySettingsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencySettings
   */
  select?: Prisma.AgencySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencySettings
   */
  omit?: Prisma.AgencySettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencySettingsInclude<ExtArgs> | null
  /**
   * Filter, which AgencySettings to fetch.
   */
  where?: Prisma.AgencySettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgencySettings to fetch.
   */
  orderBy?: Prisma.AgencySettingsOrderByWithRelationInput | Prisma.AgencySettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AgencySettings.
   */
  cursor?: Prisma.AgencySettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgencySettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgencySettings.
   */
  skip?: number
  distinct?: Prisma.AgencySettingsScalarFieldEnum | Prisma.AgencySettingsScalarFieldEnum[]
}

/**
 * AgencySettings create
 */
export type AgencySettingsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencySettings
   */
  select?: Prisma.AgencySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencySettings
   */
  omit?: Prisma.AgencySettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencySettingsInclude<ExtArgs> | null
  /**
   * The data needed to create a AgencySettings.
   */
  data: Prisma.XOR<Prisma.AgencySettingsCreateInput, Prisma.AgencySettingsUncheckedCreateInput>
}

/**
 * AgencySettings createMany
 */
export type AgencySettingsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AgencySettings.
   */
  data: Prisma.AgencySettingsCreateManyInput | Prisma.AgencySettingsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AgencySettings createManyAndReturn
 */
export type AgencySettingsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencySettings
   */
  select?: Prisma.AgencySettingsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgencySettings
   */
  omit?: Prisma.AgencySettingsOmit<ExtArgs> | null
  /**
   * The data used to create many AgencySettings.
   */
  data: Prisma.AgencySettingsCreateManyInput | Prisma.AgencySettingsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencySettingsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AgencySettings update
 */
export type AgencySettingsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencySettings
   */
  select?: Prisma.AgencySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencySettings
   */
  omit?: Prisma.AgencySettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencySettingsInclude<ExtArgs> | null
  /**
   * The data needed to update a AgencySettings.
   */
  data: Prisma.XOR<Prisma.AgencySettingsUpdateInput, Prisma.AgencySettingsUncheckedUpdateInput>
  /**
   * Choose, which AgencySettings to update.
   */
  where: Prisma.AgencySettingsWhereUniqueInput
}

/**
 * AgencySettings updateMany
 */
export type AgencySettingsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AgencySettings.
   */
  data: Prisma.XOR<Prisma.AgencySettingsUpdateManyMutationInput, Prisma.AgencySettingsUncheckedUpdateManyInput>
  /**
   * Filter which AgencySettings to update
   */
  where?: Prisma.AgencySettingsWhereInput
  /**
   * Limit how many AgencySettings to update.
   */
  limit?: number
}

/**
 * AgencySettings updateManyAndReturn
 */
export type AgencySettingsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencySettings
   */
  select?: Prisma.AgencySettingsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgencySettings
   */
  omit?: Prisma.AgencySettingsOmit<ExtArgs> | null
  /**
   * The data used to update AgencySettings.
   */
  data: Prisma.XOR<Prisma.AgencySettingsUpdateManyMutationInput, Prisma.AgencySettingsUncheckedUpdateManyInput>
  /**
   * Filter which AgencySettings to update
   */
  where?: Prisma.AgencySettingsWhereInput
  /**
   * Limit how many AgencySettings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencySettingsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AgencySettings upsert
 */
export type AgencySettingsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencySettings
   */
  select?: Prisma.AgencySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencySettings
   */
  omit?: Prisma.AgencySettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencySettingsInclude<ExtArgs> | null
  /**
   * The filter to search for the AgencySettings to update in case it exists.
   */
  where: Prisma.AgencySettingsWhereUniqueInput
  /**
   * In case the AgencySettings found by the `where` argument doesn't exist, create a new AgencySettings with this data.
   */
  create: Prisma.XOR<Prisma.AgencySettingsCreateInput, Prisma.AgencySettingsUncheckedCreateInput>
  /**
   * In case the AgencySettings was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgencySettingsUpdateInput, Prisma.AgencySettingsUncheckedUpdateInput>
}

/**
 * AgencySettings delete
 */
export type AgencySettingsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencySettings
   */
  select?: Prisma.AgencySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencySettings
   */
  omit?: Prisma.AgencySettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencySettingsInclude<ExtArgs> | null
  /**
   * Filter which AgencySettings to delete.
   */
  where: Prisma.AgencySettingsWhereUniqueInput
}

/**
 * AgencySettings deleteMany
 */
export type AgencySettingsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgencySettings to delete
   */
  where?: Prisma.AgencySettingsWhereInput
  /**
   * Limit how many AgencySettings to delete.
   */
  limit?: number
}

/**
 * AgencySettings without action
 */
export type AgencySettingsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencySettings
   */
  select?: Prisma.AgencySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencySettings
   */
  omit?: Prisma.AgencySettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencySettingsInclude<ExtArgs> | null
}
