
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ClientAdApproval` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ClientAdApproval
 * 
 */
export type ClientAdApprovalModel = runtime.Types.Result.DefaultSelection<Prisma.$ClientAdApprovalPayload>

export type AggregateClientAdApproval = {
  _count: ClientAdApprovalCountAggregateOutputType | null
  _avg: ClientAdApprovalAvgAggregateOutputType | null
  _sum: ClientAdApprovalSumAggregateOutputType | null
  _min: ClientAdApprovalMinAggregateOutputType | null
  _max: ClientAdApprovalMaxAggregateOutputType | null
}

export type ClientAdApprovalAvgAggregateOutputType = {
  revisionNumber: number | null
}

export type ClientAdApprovalSumAggregateOutputType = {
  revisionNumber: number | null
}

export type ClientAdApprovalMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  adId: string | null
  clientAccountId: string | null
  status: string | null
  feedback: string | null
  submittedAt: Date | null
  approvedAt: Date | null
  approvedBy: string | null
  revisionNumber: number | null
  previousApprovalId: string | null
  submittedBy: string | null
  submitterMessage: string | null
}

export type ClientAdApprovalMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  adId: string | null
  clientAccountId: string | null
  status: string | null
  feedback: string | null
  submittedAt: Date | null
  approvedAt: Date | null
  approvedBy: string | null
  revisionNumber: number | null
  previousApprovalId: string | null
  submittedBy: string | null
  submitterMessage: string | null
}

export type ClientAdApprovalCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  adId: number
  clientAccountId: number
  status: number
  feedback: number
  requestedChanges: number
  submittedAt: number
  approvedAt: number
  approvedBy: number
  revisionNumber: number
  previousApprovalId: number
  submittedBy: number
  submitterMessage: number
  _all: number
}


export type ClientAdApprovalAvgAggregateInputType = {
  revisionNumber?: true
}

export type ClientAdApprovalSumAggregateInputType = {
  revisionNumber?: true
}

export type ClientAdApprovalMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  adId?: true
  clientAccountId?: true
  status?: true
  feedback?: true
  submittedAt?: true
  approvedAt?: true
  approvedBy?: true
  revisionNumber?: true
  previousApprovalId?: true
  submittedBy?: true
  submitterMessage?: true
}

export type ClientAdApprovalMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  adId?: true
  clientAccountId?: true
  status?: true
  feedback?: true
  submittedAt?: true
  approvedAt?: true
  approvedBy?: true
  revisionNumber?: true
  previousApprovalId?: true
  submittedBy?: true
  submitterMessage?: true
}

export type ClientAdApprovalCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  adId?: true
  clientAccountId?: true
  status?: true
  feedback?: true
  requestedChanges?: true
  submittedAt?: true
  approvedAt?: true
  approvedBy?: true
  revisionNumber?: true
  previousApprovalId?: true
  submittedBy?: true
  submitterMessage?: true
  _all?: true
}

export type ClientAdApprovalAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClientAdApproval to aggregate.
   */
  where?: Prisma.ClientAdApprovalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientAdApprovals to fetch.
   */
  orderBy?: Prisma.ClientAdApprovalOrderByWithRelationInput | Prisma.ClientAdApprovalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ClientAdApprovalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientAdApprovals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientAdApprovals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ClientAdApprovals
  **/
  _count?: true | ClientAdApprovalCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ClientAdApprovalAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ClientAdApprovalSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ClientAdApprovalMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ClientAdApprovalMaxAggregateInputType
}

export type GetClientAdApprovalAggregateType<T extends ClientAdApprovalAggregateArgs> = {
      [P in keyof T & keyof AggregateClientAdApproval]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClientAdApproval[P]>
    : Prisma.GetScalarType<T[P], AggregateClientAdApproval[P]>
}




export type ClientAdApprovalGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClientAdApprovalWhereInput
  orderBy?: Prisma.ClientAdApprovalOrderByWithAggregationInput | Prisma.ClientAdApprovalOrderByWithAggregationInput[]
  by: Prisma.ClientAdApprovalScalarFieldEnum[] | Prisma.ClientAdApprovalScalarFieldEnum
  having?: Prisma.ClientAdApprovalScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ClientAdApprovalCountAggregateInputType | true
  _avg?: ClientAdApprovalAvgAggregateInputType
  _sum?: ClientAdApprovalSumAggregateInputType
  _min?: ClientAdApprovalMinAggregateInputType
  _max?: ClientAdApprovalMaxAggregateInputType
}

export type ClientAdApprovalGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  adId: string
  clientAccountId: string
  status: string
  feedback: string | null
  requestedChanges: runtime.JsonValue | null
  submittedAt: Date
  approvedAt: Date | null
  approvedBy: string | null
  revisionNumber: number
  previousApprovalId: string | null
  submittedBy: string | null
  submitterMessage: string | null
  _count: ClientAdApprovalCountAggregateOutputType | null
  _avg: ClientAdApprovalAvgAggregateOutputType | null
  _sum: ClientAdApprovalSumAggregateOutputType | null
  _min: ClientAdApprovalMinAggregateOutputType | null
  _max: ClientAdApprovalMaxAggregateOutputType | null
}

type GetClientAdApprovalGroupByPayload<T extends ClientAdApprovalGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ClientAdApprovalGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ClientAdApprovalGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClientAdApprovalGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClientAdApprovalGroupByOutputType[P]>
      }
    >
  >



export type ClientAdApprovalWhereInput = {
  AND?: Prisma.ClientAdApprovalWhereInput | Prisma.ClientAdApprovalWhereInput[]
  OR?: Prisma.ClientAdApprovalWhereInput[]
  NOT?: Prisma.ClientAdApprovalWhereInput | Prisma.ClientAdApprovalWhereInput[]
  id?: Prisma.StringFilter<"ClientAdApproval"> | string
  createdAt?: Prisma.DateTimeFilter<"ClientAdApproval"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ClientAdApproval"> | Date | string
  adId?: Prisma.StringFilter<"ClientAdApproval"> | string
  clientAccountId?: Prisma.StringFilter<"ClientAdApproval"> | string
  status?: Prisma.StringFilter<"ClientAdApproval"> | string
  feedback?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  requestedChanges?: Prisma.JsonNullableFilter<"ClientAdApproval">
  submittedAt?: Prisma.DateTimeFilter<"ClientAdApproval"> | Date | string
  approvedAt?: Prisma.DateTimeNullableFilter<"ClientAdApproval"> | Date | string | null
  approvedBy?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  revisionNumber?: Prisma.IntFilter<"ClientAdApproval"> | number
  previousApprovalId?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  submittedBy?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  submitterMessage?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  Ad?: Prisma.XOR<Prisma.AdScalarRelationFilter, Prisma.AdWhereInput>
  ClientAccount?: Prisma.XOR<Prisma.ClientAccountScalarRelationFilter, Prisma.ClientAccountWhereInput>
}

export type ClientAdApprovalOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  adId?: Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  feedback?: Prisma.SortOrderInput | Prisma.SortOrder
  requestedChanges?: Prisma.SortOrderInput | Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  approvedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  approvedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  revisionNumber?: Prisma.SortOrder
  previousApprovalId?: Prisma.SortOrderInput | Prisma.SortOrder
  submittedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  submitterMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  Ad?: Prisma.AdOrderByWithRelationInput
  ClientAccount?: Prisma.ClientAccountOrderByWithRelationInput
}

export type ClientAdApprovalWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ClientAdApprovalWhereInput | Prisma.ClientAdApprovalWhereInput[]
  OR?: Prisma.ClientAdApprovalWhereInput[]
  NOT?: Prisma.ClientAdApprovalWhereInput | Prisma.ClientAdApprovalWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"ClientAdApproval"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ClientAdApproval"> | Date | string
  adId?: Prisma.StringFilter<"ClientAdApproval"> | string
  clientAccountId?: Prisma.StringFilter<"ClientAdApproval"> | string
  status?: Prisma.StringFilter<"ClientAdApproval"> | string
  feedback?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  requestedChanges?: Prisma.JsonNullableFilter<"ClientAdApproval">
  submittedAt?: Prisma.DateTimeFilter<"ClientAdApproval"> | Date | string
  approvedAt?: Prisma.DateTimeNullableFilter<"ClientAdApproval"> | Date | string | null
  approvedBy?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  revisionNumber?: Prisma.IntFilter<"ClientAdApproval"> | number
  previousApprovalId?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  submittedBy?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  submitterMessage?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  Ad?: Prisma.XOR<Prisma.AdScalarRelationFilter, Prisma.AdWhereInput>
  ClientAccount?: Prisma.XOR<Prisma.ClientAccountScalarRelationFilter, Prisma.ClientAccountWhereInput>
}, "id">

export type ClientAdApprovalOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  adId?: Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  feedback?: Prisma.SortOrderInput | Prisma.SortOrder
  requestedChanges?: Prisma.SortOrderInput | Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  approvedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  approvedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  revisionNumber?: Prisma.SortOrder
  previousApprovalId?: Prisma.SortOrderInput | Prisma.SortOrder
  submittedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  submitterMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ClientAdApprovalCountOrderByAggregateInput
  _avg?: Prisma.ClientAdApprovalAvgOrderByAggregateInput
  _max?: Prisma.ClientAdApprovalMaxOrderByAggregateInput
  _min?: Prisma.ClientAdApprovalMinOrderByAggregateInput
  _sum?: Prisma.ClientAdApprovalSumOrderByAggregateInput
}

export type ClientAdApprovalScalarWhereWithAggregatesInput = {
  AND?: Prisma.ClientAdApprovalScalarWhereWithAggregatesInput | Prisma.ClientAdApprovalScalarWhereWithAggregatesInput[]
  OR?: Prisma.ClientAdApprovalScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ClientAdApprovalScalarWhereWithAggregatesInput | Prisma.ClientAdApprovalScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ClientAdApproval"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ClientAdApproval"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ClientAdApproval"> | Date | string
  adId?: Prisma.StringWithAggregatesFilter<"ClientAdApproval"> | string
  clientAccountId?: Prisma.StringWithAggregatesFilter<"ClientAdApproval"> | string
  status?: Prisma.StringWithAggregatesFilter<"ClientAdApproval"> | string
  feedback?: Prisma.StringNullableWithAggregatesFilter<"ClientAdApproval"> | string | null
  requestedChanges?: Prisma.JsonNullableWithAggregatesFilter<"ClientAdApproval">
  submittedAt?: Prisma.DateTimeWithAggregatesFilter<"ClientAdApproval"> | Date | string
  approvedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ClientAdApproval"> | Date | string | null
  approvedBy?: Prisma.StringNullableWithAggregatesFilter<"ClientAdApproval"> | string | null
  revisionNumber?: Prisma.IntWithAggregatesFilter<"ClientAdApproval"> | number
  previousApprovalId?: Prisma.StringNullableWithAggregatesFilter<"ClientAdApproval"> | string | null
  submittedBy?: Prisma.StringNullableWithAggregatesFilter<"ClientAdApproval"> | string | null
  submitterMessage?: Prisma.StringNullableWithAggregatesFilter<"ClientAdApproval"> | string | null
}

export type ClientAdApprovalCreateInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  status?: string
  feedback?: string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Date | string
  approvedAt?: Date | string | null
  approvedBy?: string | null
  revisionNumber?: number
  previousApprovalId?: string | null
  submittedBy?: string | null
  submitterMessage?: string | null
  Ad: Prisma.AdCreateNestedOneWithoutClientAdApprovalInput
  ClientAccount: Prisma.ClientAccountCreateNestedOneWithoutClientAdApprovalInput
}

export type ClientAdApprovalUncheckedCreateInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  adId: string
  clientAccountId: string
  status?: string
  feedback?: string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Date | string
  approvedAt?: Date | string | null
  approvedBy?: string | null
  revisionNumber?: number
  previousApprovalId?: string | null
  submittedBy?: string | null
  submitterMessage?: string | null
}

export type ClientAdApprovalUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revisionNumber?: Prisma.IntFieldUpdateOperationsInput | number
  previousApprovalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submitterMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Ad?: Prisma.AdUpdateOneRequiredWithoutClientAdApprovalNestedInput
  ClientAccount?: Prisma.ClientAccountUpdateOneRequiredWithoutClientAdApprovalNestedInput
}

export type ClientAdApprovalUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  adId?: Prisma.StringFieldUpdateOperationsInput | string
  clientAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revisionNumber?: Prisma.IntFieldUpdateOperationsInput | number
  previousApprovalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submitterMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ClientAdApprovalCreateManyInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  adId: string
  clientAccountId: string
  status?: string
  feedback?: string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Date | string
  approvedAt?: Date | string | null
  approvedBy?: string | null
  revisionNumber?: number
  previousApprovalId?: string | null
  submittedBy?: string | null
  submitterMessage?: string | null
}

export type ClientAdApprovalUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revisionNumber?: Prisma.IntFieldUpdateOperationsInput | number
  previousApprovalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submitterMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ClientAdApprovalUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  adId?: Prisma.StringFieldUpdateOperationsInput | string
  clientAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revisionNumber?: Prisma.IntFieldUpdateOperationsInput | number
  previousApprovalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submitterMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ClientAdApprovalListRelationFilter = {
  every?: Prisma.ClientAdApprovalWhereInput
  some?: Prisma.ClientAdApprovalWhereInput
  none?: Prisma.ClientAdApprovalWhereInput
}

export type ClientAdApprovalOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ClientAdApprovalCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  adId?: Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  feedback?: Prisma.SortOrder
  requestedChanges?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  approvedAt?: Prisma.SortOrder
  approvedBy?: Prisma.SortOrder
  revisionNumber?: Prisma.SortOrder
  previousApprovalId?: Prisma.SortOrder
  submittedBy?: Prisma.SortOrder
  submitterMessage?: Prisma.SortOrder
}

export type ClientAdApprovalAvgOrderByAggregateInput = {
  revisionNumber?: Prisma.SortOrder
}

export type ClientAdApprovalMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  adId?: Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  feedback?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  approvedAt?: Prisma.SortOrder
  approvedBy?: Prisma.SortOrder
  revisionNumber?: Prisma.SortOrder
  previousApprovalId?: Prisma.SortOrder
  submittedBy?: Prisma.SortOrder
  submitterMessage?: Prisma.SortOrder
}

export type ClientAdApprovalMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  adId?: Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  feedback?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  approvedAt?: Prisma.SortOrder
  approvedBy?: Prisma.SortOrder
  revisionNumber?: Prisma.SortOrder
  previousApprovalId?: Prisma.SortOrder
  submittedBy?: Prisma.SortOrder
  submitterMessage?: Prisma.SortOrder
}

export type ClientAdApprovalSumOrderByAggregateInput = {
  revisionNumber?: Prisma.SortOrder
}

export type ClientAdApprovalCreateNestedManyWithoutAdInput = {
  create?: Prisma.XOR<Prisma.ClientAdApprovalCreateWithoutAdInput, Prisma.ClientAdApprovalUncheckedCreateWithoutAdInput> | Prisma.ClientAdApprovalCreateWithoutAdInput[] | Prisma.ClientAdApprovalUncheckedCreateWithoutAdInput[]
  connectOrCreate?: Prisma.ClientAdApprovalCreateOrConnectWithoutAdInput | Prisma.ClientAdApprovalCreateOrConnectWithoutAdInput[]
  createMany?: Prisma.ClientAdApprovalCreateManyAdInputEnvelope
  connect?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
}

export type ClientAdApprovalUncheckedCreateNestedManyWithoutAdInput = {
  create?: Prisma.XOR<Prisma.ClientAdApprovalCreateWithoutAdInput, Prisma.ClientAdApprovalUncheckedCreateWithoutAdInput> | Prisma.ClientAdApprovalCreateWithoutAdInput[] | Prisma.ClientAdApprovalUncheckedCreateWithoutAdInput[]
  connectOrCreate?: Prisma.ClientAdApprovalCreateOrConnectWithoutAdInput | Prisma.ClientAdApprovalCreateOrConnectWithoutAdInput[]
  createMany?: Prisma.ClientAdApprovalCreateManyAdInputEnvelope
  connect?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
}

export type ClientAdApprovalUpdateManyWithoutAdNestedInput = {
  create?: Prisma.XOR<Prisma.ClientAdApprovalCreateWithoutAdInput, Prisma.ClientAdApprovalUncheckedCreateWithoutAdInput> | Prisma.ClientAdApprovalCreateWithoutAdInput[] | Prisma.ClientAdApprovalUncheckedCreateWithoutAdInput[]
  connectOrCreate?: Prisma.ClientAdApprovalCreateOrConnectWithoutAdInput | Prisma.ClientAdApprovalCreateOrConnectWithoutAdInput[]
  upsert?: Prisma.ClientAdApprovalUpsertWithWhereUniqueWithoutAdInput | Prisma.ClientAdApprovalUpsertWithWhereUniqueWithoutAdInput[]
  createMany?: Prisma.ClientAdApprovalCreateManyAdInputEnvelope
  set?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  disconnect?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  delete?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  connect?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  update?: Prisma.ClientAdApprovalUpdateWithWhereUniqueWithoutAdInput | Prisma.ClientAdApprovalUpdateWithWhereUniqueWithoutAdInput[]
  updateMany?: Prisma.ClientAdApprovalUpdateManyWithWhereWithoutAdInput | Prisma.ClientAdApprovalUpdateManyWithWhereWithoutAdInput[]
  deleteMany?: Prisma.ClientAdApprovalScalarWhereInput | Prisma.ClientAdApprovalScalarWhereInput[]
}

export type ClientAdApprovalUncheckedUpdateManyWithoutAdNestedInput = {
  create?: Prisma.XOR<Prisma.ClientAdApprovalCreateWithoutAdInput, Prisma.ClientAdApprovalUncheckedCreateWithoutAdInput> | Prisma.ClientAdApprovalCreateWithoutAdInput[] | Prisma.ClientAdApprovalUncheckedCreateWithoutAdInput[]
  connectOrCreate?: Prisma.ClientAdApprovalCreateOrConnectWithoutAdInput | Prisma.ClientAdApprovalCreateOrConnectWithoutAdInput[]
  upsert?: Prisma.ClientAdApprovalUpsertWithWhereUniqueWithoutAdInput | Prisma.ClientAdApprovalUpsertWithWhereUniqueWithoutAdInput[]
  createMany?: Prisma.ClientAdApprovalCreateManyAdInputEnvelope
  set?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  disconnect?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  delete?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  connect?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  update?: Prisma.ClientAdApprovalUpdateWithWhereUniqueWithoutAdInput | Prisma.ClientAdApprovalUpdateWithWhereUniqueWithoutAdInput[]
  updateMany?: Prisma.ClientAdApprovalUpdateManyWithWhereWithoutAdInput | Prisma.ClientAdApprovalUpdateManyWithWhereWithoutAdInput[]
  deleteMany?: Prisma.ClientAdApprovalScalarWhereInput | Prisma.ClientAdApprovalScalarWhereInput[]
}

export type ClientAdApprovalCreateNestedManyWithoutClientAccountInput = {
  create?: Prisma.XOR<Prisma.ClientAdApprovalCreateWithoutClientAccountInput, Prisma.ClientAdApprovalUncheckedCreateWithoutClientAccountInput> | Prisma.ClientAdApprovalCreateWithoutClientAccountInput[] | Prisma.ClientAdApprovalUncheckedCreateWithoutClientAccountInput[]
  connectOrCreate?: Prisma.ClientAdApprovalCreateOrConnectWithoutClientAccountInput | Prisma.ClientAdApprovalCreateOrConnectWithoutClientAccountInput[]
  createMany?: Prisma.ClientAdApprovalCreateManyClientAccountInputEnvelope
  connect?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
}

export type ClientAdApprovalUncheckedCreateNestedManyWithoutClientAccountInput = {
  create?: Prisma.XOR<Prisma.ClientAdApprovalCreateWithoutClientAccountInput, Prisma.ClientAdApprovalUncheckedCreateWithoutClientAccountInput> | Prisma.ClientAdApprovalCreateWithoutClientAccountInput[] | Prisma.ClientAdApprovalUncheckedCreateWithoutClientAccountInput[]
  connectOrCreate?: Prisma.ClientAdApprovalCreateOrConnectWithoutClientAccountInput | Prisma.ClientAdApprovalCreateOrConnectWithoutClientAccountInput[]
  createMany?: Prisma.ClientAdApprovalCreateManyClientAccountInputEnvelope
  connect?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
}

export type ClientAdApprovalUpdateManyWithoutClientAccountNestedInput = {
  create?: Prisma.XOR<Prisma.ClientAdApprovalCreateWithoutClientAccountInput, Prisma.ClientAdApprovalUncheckedCreateWithoutClientAccountInput> | Prisma.ClientAdApprovalCreateWithoutClientAccountInput[] | Prisma.ClientAdApprovalUncheckedCreateWithoutClientAccountInput[]
  connectOrCreate?: Prisma.ClientAdApprovalCreateOrConnectWithoutClientAccountInput | Prisma.ClientAdApprovalCreateOrConnectWithoutClientAccountInput[]
  upsert?: Prisma.ClientAdApprovalUpsertWithWhereUniqueWithoutClientAccountInput | Prisma.ClientAdApprovalUpsertWithWhereUniqueWithoutClientAccountInput[]
  createMany?: Prisma.ClientAdApprovalCreateManyClientAccountInputEnvelope
  set?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  disconnect?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  delete?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  connect?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  update?: Prisma.ClientAdApprovalUpdateWithWhereUniqueWithoutClientAccountInput | Prisma.ClientAdApprovalUpdateWithWhereUniqueWithoutClientAccountInput[]
  updateMany?: Prisma.ClientAdApprovalUpdateManyWithWhereWithoutClientAccountInput | Prisma.ClientAdApprovalUpdateManyWithWhereWithoutClientAccountInput[]
  deleteMany?: Prisma.ClientAdApprovalScalarWhereInput | Prisma.ClientAdApprovalScalarWhereInput[]
}

export type ClientAdApprovalUncheckedUpdateManyWithoutClientAccountNestedInput = {
  create?: Prisma.XOR<Prisma.ClientAdApprovalCreateWithoutClientAccountInput, Prisma.ClientAdApprovalUncheckedCreateWithoutClientAccountInput> | Prisma.ClientAdApprovalCreateWithoutClientAccountInput[] | Prisma.ClientAdApprovalUncheckedCreateWithoutClientAccountInput[]
  connectOrCreate?: Prisma.ClientAdApprovalCreateOrConnectWithoutClientAccountInput | Prisma.ClientAdApprovalCreateOrConnectWithoutClientAccountInput[]
  upsert?: Prisma.ClientAdApprovalUpsertWithWhereUniqueWithoutClientAccountInput | Prisma.ClientAdApprovalUpsertWithWhereUniqueWithoutClientAccountInput[]
  createMany?: Prisma.ClientAdApprovalCreateManyClientAccountInputEnvelope
  set?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  disconnect?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  delete?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  connect?: Prisma.ClientAdApprovalWhereUniqueInput | Prisma.ClientAdApprovalWhereUniqueInput[]
  update?: Prisma.ClientAdApprovalUpdateWithWhereUniqueWithoutClientAccountInput | Prisma.ClientAdApprovalUpdateWithWhereUniqueWithoutClientAccountInput[]
  updateMany?: Prisma.ClientAdApprovalUpdateManyWithWhereWithoutClientAccountInput | Prisma.ClientAdApprovalUpdateManyWithWhereWithoutClientAccountInput[]
  deleteMany?: Prisma.ClientAdApprovalScalarWhereInput | Prisma.ClientAdApprovalScalarWhereInput[]
}

export type ClientAdApprovalCreateWithoutAdInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  status?: string
  feedback?: string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Date | string
  approvedAt?: Date | string | null
  approvedBy?: string | null
  revisionNumber?: number
  previousApprovalId?: string | null
  submittedBy?: string | null
  submitterMessage?: string | null
  ClientAccount: Prisma.ClientAccountCreateNestedOneWithoutClientAdApprovalInput
}

export type ClientAdApprovalUncheckedCreateWithoutAdInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  clientAccountId: string
  status?: string
  feedback?: string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Date | string
  approvedAt?: Date | string | null
  approvedBy?: string | null
  revisionNumber?: number
  previousApprovalId?: string | null
  submittedBy?: string | null
  submitterMessage?: string | null
}

export type ClientAdApprovalCreateOrConnectWithoutAdInput = {
  where: Prisma.ClientAdApprovalWhereUniqueInput
  create: Prisma.XOR<Prisma.ClientAdApprovalCreateWithoutAdInput, Prisma.ClientAdApprovalUncheckedCreateWithoutAdInput>
}

export type ClientAdApprovalCreateManyAdInputEnvelope = {
  data: Prisma.ClientAdApprovalCreateManyAdInput | Prisma.ClientAdApprovalCreateManyAdInput[]
  skipDuplicates?: boolean
}

export type ClientAdApprovalUpsertWithWhereUniqueWithoutAdInput = {
  where: Prisma.ClientAdApprovalWhereUniqueInput
  update: Prisma.XOR<Prisma.ClientAdApprovalUpdateWithoutAdInput, Prisma.ClientAdApprovalUncheckedUpdateWithoutAdInput>
  create: Prisma.XOR<Prisma.ClientAdApprovalCreateWithoutAdInput, Prisma.ClientAdApprovalUncheckedCreateWithoutAdInput>
}

export type ClientAdApprovalUpdateWithWhereUniqueWithoutAdInput = {
  where: Prisma.ClientAdApprovalWhereUniqueInput
  data: Prisma.XOR<Prisma.ClientAdApprovalUpdateWithoutAdInput, Prisma.ClientAdApprovalUncheckedUpdateWithoutAdInput>
}

export type ClientAdApprovalUpdateManyWithWhereWithoutAdInput = {
  where: Prisma.ClientAdApprovalScalarWhereInput
  data: Prisma.XOR<Prisma.ClientAdApprovalUpdateManyMutationInput, Prisma.ClientAdApprovalUncheckedUpdateManyWithoutAdInput>
}

export type ClientAdApprovalScalarWhereInput = {
  AND?: Prisma.ClientAdApprovalScalarWhereInput | Prisma.ClientAdApprovalScalarWhereInput[]
  OR?: Prisma.ClientAdApprovalScalarWhereInput[]
  NOT?: Prisma.ClientAdApprovalScalarWhereInput | Prisma.ClientAdApprovalScalarWhereInput[]
  id?: Prisma.StringFilter<"ClientAdApproval"> | string
  createdAt?: Prisma.DateTimeFilter<"ClientAdApproval"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ClientAdApproval"> | Date | string
  adId?: Prisma.StringFilter<"ClientAdApproval"> | string
  clientAccountId?: Prisma.StringFilter<"ClientAdApproval"> | string
  status?: Prisma.StringFilter<"ClientAdApproval"> | string
  feedback?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  requestedChanges?: Prisma.JsonNullableFilter<"ClientAdApproval">
  submittedAt?: Prisma.DateTimeFilter<"ClientAdApproval"> | Date | string
  approvedAt?: Prisma.DateTimeNullableFilter<"ClientAdApproval"> | Date | string | null
  approvedBy?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  revisionNumber?: Prisma.IntFilter<"ClientAdApproval"> | number
  previousApprovalId?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  submittedBy?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
  submitterMessage?: Prisma.StringNullableFilter<"ClientAdApproval"> | string | null
}

export type ClientAdApprovalCreateWithoutClientAccountInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  status?: string
  feedback?: string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Date | string
  approvedAt?: Date | string | null
  approvedBy?: string | null
  revisionNumber?: number
  previousApprovalId?: string | null
  submittedBy?: string | null
  submitterMessage?: string | null
  Ad: Prisma.AdCreateNestedOneWithoutClientAdApprovalInput
}

export type ClientAdApprovalUncheckedCreateWithoutClientAccountInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  adId: string
  status?: string
  feedback?: string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Date | string
  approvedAt?: Date | string | null
  approvedBy?: string | null
  revisionNumber?: number
  previousApprovalId?: string | null
  submittedBy?: string | null
  submitterMessage?: string | null
}

export type ClientAdApprovalCreateOrConnectWithoutClientAccountInput = {
  where: Prisma.ClientAdApprovalWhereUniqueInput
  create: Prisma.XOR<Prisma.ClientAdApprovalCreateWithoutClientAccountInput, Prisma.ClientAdApprovalUncheckedCreateWithoutClientAccountInput>
}

export type ClientAdApprovalCreateManyClientAccountInputEnvelope = {
  data: Prisma.ClientAdApprovalCreateManyClientAccountInput | Prisma.ClientAdApprovalCreateManyClientAccountInput[]
  skipDuplicates?: boolean
}

export type ClientAdApprovalUpsertWithWhereUniqueWithoutClientAccountInput = {
  where: Prisma.ClientAdApprovalWhereUniqueInput
  update: Prisma.XOR<Prisma.ClientAdApprovalUpdateWithoutClientAccountInput, Prisma.ClientAdApprovalUncheckedUpdateWithoutClientAccountInput>
  create: Prisma.XOR<Prisma.ClientAdApprovalCreateWithoutClientAccountInput, Prisma.ClientAdApprovalUncheckedCreateWithoutClientAccountInput>
}

export type ClientAdApprovalUpdateWithWhereUniqueWithoutClientAccountInput = {
  where: Prisma.ClientAdApprovalWhereUniqueInput
  data: Prisma.XOR<Prisma.ClientAdApprovalUpdateWithoutClientAccountInput, Prisma.ClientAdApprovalUncheckedUpdateWithoutClientAccountInput>
}

export type ClientAdApprovalUpdateManyWithWhereWithoutClientAccountInput = {
  where: Prisma.ClientAdApprovalScalarWhereInput
  data: Prisma.XOR<Prisma.ClientAdApprovalUpdateManyMutationInput, Prisma.ClientAdApprovalUncheckedUpdateManyWithoutClientAccountInput>
}

export type ClientAdApprovalCreateManyAdInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  clientAccountId: string
  status?: string
  feedback?: string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Date | string
  approvedAt?: Date | string | null
  approvedBy?: string | null
  revisionNumber?: number
  previousApprovalId?: string | null
  submittedBy?: string | null
  submitterMessage?: string | null
}

export type ClientAdApprovalUpdateWithoutAdInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revisionNumber?: Prisma.IntFieldUpdateOperationsInput | number
  previousApprovalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submitterMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ClientAccount?: Prisma.ClientAccountUpdateOneRequiredWithoutClientAdApprovalNestedInput
}

export type ClientAdApprovalUncheckedUpdateWithoutAdInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revisionNumber?: Prisma.IntFieldUpdateOperationsInput | number
  previousApprovalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submitterMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ClientAdApprovalUncheckedUpdateManyWithoutAdInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revisionNumber?: Prisma.IntFieldUpdateOperationsInput | number
  previousApprovalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submitterMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ClientAdApprovalCreateManyClientAccountInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  adId: string
  status?: string
  feedback?: string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Date | string
  approvedAt?: Date | string | null
  approvedBy?: string | null
  revisionNumber?: number
  previousApprovalId?: string | null
  submittedBy?: string | null
  submitterMessage?: string | null
}

export type ClientAdApprovalUpdateWithoutClientAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revisionNumber?: Prisma.IntFieldUpdateOperationsInput | number
  previousApprovalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submitterMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Ad?: Prisma.AdUpdateOneRequiredWithoutClientAdApprovalNestedInput
}

export type ClientAdApprovalUncheckedUpdateWithoutClientAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  adId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revisionNumber?: Prisma.IntFieldUpdateOperationsInput | number
  previousApprovalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submitterMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ClientAdApprovalUncheckedUpdateManyWithoutClientAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  adId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requestedChanges?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revisionNumber?: Prisma.IntFieldUpdateOperationsInput | number
  previousApprovalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submitterMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type ClientAdApprovalSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  adId?: boolean
  clientAccountId?: boolean
  status?: boolean
  feedback?: boolean
  requestedChanges?: boolean
  submittedAt?: boolean
  approvedAt?: boolean
  approvedBy?: boolean
  revisionNumber?: boolean
  previousApprovalId?: boolean
  submittedBy?: boolean
  submitterMessage?: boolean
  Ad?: boolean | Prisma.AdDefaultArgs<ExtArgs>
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clientAdApproval"]>

export type ClientAdApprovalSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  adId?: boolean
  clientAccountId?: boolean
  status?: boolean
  feedback?: boolean
  requestedChanges?: boolean
  submittedAt?: boolean
  approvedAt?: boolean
  approvedBy?: boolean
  revisionNumber?: boolean
  previousApprovalId?: boolean
  submittedBy?: boolean
  submitterMessage?: boolean
  Ad?: boolean | Prisma.AdDefaultArgs<ExtArgs>
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clientAdApproval"]>

export type ClientAdApprovalSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  adId?: boolean
  clientAccountId?: boolean
  status?: boolean
  feedback?: boolean
  requestedChanges?: boolean
  submittedAt?: boolean
  approvedAt?: boolean
  approvedBy?: boolean
  revisionNumber?: boolean
  previousApprovalId?: boolean
  submittedBy?: boolean
  submitterMessage?: boolean
  Ad?: boolean | Prisma.AdDefaultArgs<ExtArgs>
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clientAdApproval"]>

export type ClientAdApprovalSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  adId?: boolean
  clientAccountId?: boolean
  status?: boolean
  feedback?: boolean
  requestedChanges?: boolean
  submittedAt?: boolean
  approvedAt?: boolean
  approvedBy?: boolean
  revisionNumber?: boolean
  previousApprovalId?: boolean
  submittedBy?: boolean
  submitterMessage?: boolean
}

export type ClientAdApprovalOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "adId" | "clientAccountId" | "status" | "feedback" | "requestedChanges" | "submittedAt" | "approvedAt" | "approvedBy" | "revisionNumber" | "previousApprovalId" | "submittedBy" | "submitterMessage", ExtArgs["result"]["clientAdApproval"]>
export type ClientAdApprovalInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Ad?: boolean | Prisma.AdDefaultArgs<ExtArgs>
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}
export type ClientAdApprovalIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Ad?: boolean | Prisma.AdDefaultArgs<ExtArgs>
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}
export type ClientAdApprovalIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Ad?: boolean | Prisma.AdDefaultArgs<ExtArgs>
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}

export type $ClientAdApprovalPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ClientAdApproval"
  objects: {
    Ad: Prisma.$AdPayload<ExtArgs>
    ClientAccount: Prisma.$ClientAccountPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    adId: string
    clientAccountId: string
    status: string
    feedback: string | null
    requestedChanges: runtime.JsonValue | null
    submittedAt: Date
    approvedAt: Date | null
    approvedBy: string | null
    revisionNumber: number
    previousApprovalId: string | null
    submittedBy: string | null
    submitterMessage: string | null
  }, ExtArgs["result"]["clientAdApproval"]>
  composites: {}
}

export type ClientAdApprovalGetPayload<S extends boolean | null | undefined | ClientAdApprovalDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ClientAdApprovalPayload, S>

export type ClientAdApprovalCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ClientAdApprovalFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ClientAdApprovalCountAggregateInputType | true
  }

export interface ClientAdApprovalDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ClientAdApproval'], meta: { name: 'ClientAdApproval' } }
  /**
   * Find zero or one ClientAdApproval that matches the filter.
   * @param {ClientAdApprovalFindUniqueArgs} args - Arguments to find a ClientAdApproval
   * @example
   * // Get one ClientAdApproval
   * const clientAdApproval = await prisma.clientAdApproval.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClientAdApprovalFindUniqueArgs>(args: Prisma.SelectSubset<T, ClientAdApprovalFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ClientAdApprovalClient<runtime.Types.Result.GetResult<Prisma.$ClientAdApprovalPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ClientAdApproval that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClientAdApprovalFindUniqueOrThrowArgs} args - Arguments to find a ClientAdApproval
   * @example
   * // Get one ClientAdApproval
   * const clientAdApproval = await prisma.clientAdApproval.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClientAdApprovalFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ClientAdApprovalFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClientAdApprovalClient<runtime.Types.Result.GetResult<Prisma.$ClientAdApprovalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClientAdApproval that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAdApprovalFindFirstArgs} args - Arguments to find a ClientAdApproval
   * @example
   * // Get one ClientAdApproval
   * const clientAdApproval = await prisma.clientAdApproval.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClientAdApprovalFindFirstArgs>(args?: Prisma.SelectSubset<T, ClientAdApprovalFindFirstArgs<ExtArgs>>): Prisma.Prisma__ClientAdApprovalClient<runtime.Types.Result.GetResult<Prisma.$ClientAdApprovalPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClientAdApproval that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAdApprovalFindFirstOrThrowArgs} args - Arguments to find a ClientAdApproval
   * @example
   * // Get one ClientAdApproval
   * const clientAdApproval = await prisma.clientAdApproval.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClientAdApprovalFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ClientAdApprovalFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClientAdApprovalClient<runtime.Types.Result.GetResult<Prisma.$ClientAdApprovalPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ClientAdApprovals that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAdApprovalFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ClientAdApprovals
   * const clientAdApprovals = await prisma.clientAdApproval.findMany()
   * 
   * // Get first 10 ClientAdApprovals
   * const clientAdApprovals = await prisma.clientAdApproval.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const clientAdApprovalWithIdOnly = await prisma.clientAdApproval.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ClientAdApprovalFindManyArgs>(args?: Prisma.SelectSubset<T, ClientAdApprovalFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientAdApprovalPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ClientAdApproval.
   * @param {ClientAdApprovalCreateArgs} args - Arguments to create a ClientAdApproval.
   * @example
   * // Create one ClientAdApproval
   * const ClientAdApproval = await prisma.clientAdApproval.create({
   *   data: {
   *     // ... data to create a ClientAdApproval
   *   }
   * })
   * 
   */
  create<T extends ClientAdApprovalCreateArgs>(args: Prisma.SelectSubset<T, ClientAdApprovalCreateArgs<ExtArgs>>): Prisma.Prisma__ClientAdApprovalClient<runtime.Types.Result.GetResult<Prisma.$ClientAdApprovalPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ClientAdApprovals.
   * @param {ClientAdApprovalCreateManyArgs} args - Arguments to create many ClientAdApprovals.
   * @example
   * // Create many ClientAdApprovals
   * const clientAdApproval = await prisma.clientAdApproval.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ClientAdApprovalCreateManyArgs>(args?: Prisma.SelectSubset<T, ClientAdApprovalCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ClientAdApprovals and returns the data saved in the database.
   * @param {ClientAdApprovalCreateManyAndReturnArgs} args - Arguments to create many ClientAdApprovals.
   * @example
   * // Create many ClientAdApprovals
   * const clientAdApproval = await prisma.clientAdApproval.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ClientAdApprovals and only return the `id`
   * const clientAdApprovalWithIdOnly = await prisma.clientAdApproval.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ClientAdApprovalCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ClientAdApprovalCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientAdApprovalPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ClientAdApproval.
   * @param {ClientAdApprovalDeleteArgs} args - Arguments to delete one ClientAdApproval.
   * @example
   * // Delete one ClientAdApproval
   * const ClientAdApproval = await prisma.clientAdApproval.delete({
   *   where: {
   *     // ... filter to delete one ClientAdApproval
   *   }
   * })
   * 
   */
  delete<T extends ClientAdApprovalDeleteArgs>(args: Prisma.SelectSubset<T, ClientAdApprovalDeleteArgs<ExtArgs>>): Prisma.Prisma__ClientAdApprovalClient<runtime.Types.Result.GetResult<Prisma.$ClientAdApprovalPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ClientAdApproval.
   * @param {ClientAdApprovalUpdateArgs} args - Arguments to update one ClientAdApproval.
   * @example
   * // Update one ClientAdApproval
   * const clientAdApproval = await prisma.clientAdApproval.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ClientAdApprovalUpdateArgs>(args: Prisma.SelectSubset<T, ClientAdApprovalUpdateArgs<ExtArgs>>): Prisma.Prisma__ClientAdApprovalClient<runtime.Types.Result.GetResult<Prisma.$ClientAdApprovalPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ClientAdApprovals.
   * @param {ClientAdApprovalDeleteManyArgs} args - Arguments to filter ClientAdApprovals to delete.
   * @example
   * // Delete a few ClientAdApprovals
   * const { count } = await prisma.clientAdApproval.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ClientAdApprovalDeleteManyArgs>(args?: Prisma.SelectSubset<T, ClientAdApprovalDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ClientAdApprovals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAdApprovalUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ClientAdApprovals
   * const clientAdApproval = await prisma.clientAdApproval.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ClientAdApprovalUpdateManyArgs>(args: Prisma.SelectSubset<T, ClientAdApprovalUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ClientAdApprovals and returns the data updated in the database.
   * @param {ClientAdApprovalUpdateManyAndReturnArgs} args - Arguments to update many ClientAdApprovals.
   * @example
   * // Update many ClientAdApprovals
   * const clientAdApproval = await prisma.clientAdApproval.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ClientAdApprovals and only return the `id`
   * const clientAdApprovalWithIdOnly = await prisma.clientAdApproval.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ClientAdApprovalUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ClientAdApprovalUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientAdApprovalPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ClientAdApproval.
   * @param {ClientAdApprovalUpsertArgs} args - Arguments to update or create a ClientAdApproval.
   * @example
   * // Update or create a ClientAdApproval
   * const clientAdApproval = await prisma.clientAdApproval.upsert({
   *   create: {
   *     // ... data to create a ClientAdApproval
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ClientAdApproval we want to update
   *   }
   * })
   */
  upsert<T extends ClientAdApprovalUpsertArgs>(args: Prisma.SelectSubset<T, ClientAdApprovalUpsertArgs<ExtArgs>>): Prisma.Prisma__ClientAdApprovalClient<runtime.Types.Result.GetResult<Prisma.$ClientAdApprovalPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ClientAdApprovals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAdApprovalCountArgs} args - Arguments to filter ClientAdApprovals to count.
   * @example
   * // Count the number of ClientAdApprovals
   * const count = await prisma.clientAdApproval.count({
   *   where: {
   *     // ... the filter for the ClientAdApprovals we want to count
   *   }
   * })
  **/
  count<T extends ClientAdApprovalCountArgs>(
    args?: Prisma.Subset<T, ClientAdApprovalCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClientAdApprovalCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ClientAdApproval.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAdApprovalAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ClientAdApprovalAggregateArgs>(args: Prisma.Subset<T, ClientAdApprovalAggregateArgs>): Prisma.PrismaPromise<GetClientAdApprovalAggregateType<T>>

  /**
   * Group by ClientAdApproval.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAdApprovalGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ClientAdApprovalGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ClientAdApprovalGroupByArgs['orderBy'] }
      : { orderBy?: ClientAdApprovalGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ClientAdApprovalGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClientAdApprovalGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ClientAdApproval model
 */
readonly fields: ClientAdApprovalFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ClientAdApproval.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClientAdApprovalClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Ad<T extends Prisma.AdDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AdDefaultArgs<ExtArgs>>): Prisma.Prisma__AdClient<runtime.Types.Result.GetResult<Prisma.$AdPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  ClientAccount<T extends Prisma.ClientAccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClientAccountDefaultArgs<ExtArgs>>): Prisma.Prisma__ClientAccountClient<runtime.Types.Result.GetResult<Prisma.$ClientAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ClientAdApproval model
 */
export interface ClientAdApprovalFieldRefs {
  readonly id: Prisma.FieldRef<"ClientAdApproval", 'String'>
  readonly createdAt: Prisma.FieldRef<"ClientAdApproval", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ClientAdApproval", 'DateTime'>
  readonly adId: Prisma.FieldRef<"ClientAdApproval", 'String'>
  readonly clientAccountId: Prisma.FieldRef<"ClientAdApproval", 'String'>
  readonly status: Prisma.FieldRef<"ClientAdApproval", 'String'>
  readonly feedback: Prisma.FieldRef<"ClientAdApproval", 'String'>
  readonly requestedChanges: Prisma.FieldRef<"ClientAdApproval", 'Json'>
  readonly submittedAt: Prisma.FieldRef<"ClientAdApproval", 'DateTime'>
  readonly approvedAt: Prisma.FieldRef<"ClientAdApproval", 'DateTime'>
  readonly approvedBy: Prisma.FieldRef<"ClientAdApproval", 'String'>
  readonly revisionNumber: Prisma.FieldRef<"ClientAdApproval", 'Int'>
  readonly previousApprovalId: Prisma.FieldRef<"ClientAdApproval", 'String'>
  readonly submittedBy: Prisma.FieldRef<"ClientAdApproval", 'String'>
  readonly submitterMessage: Prisma.FieldRef<"ClientAdApproval", 'String'>
}
    

// Custom InputTypes
/**
 * ClientAdApproval findUnique
 */
export type ClientAdApprovalFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAdApproval
   */
  select?: Prisma.ClientAdApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAdApproval
   */
  omit?: Prisma.ClientAdApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAdApprovalInclude<ExtArgs> | null
  /**
   * Filter, which ClientAdApproval to fetch.
   */
  where: Prisma.ClientAdApprovalWhereUniqueInput
}

/**
 * ClientAdApproval findUniqueOrThrow
 */
export type ClientAdApprovalFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAdApproval
   */
  select?: Prisma.ClientAdApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAdApproval
   */
  omit?: Prisma.ClientAdApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAdApprovalInclude<ExtArgs> | null
  /**
   * Filter, which ClientAdApproval to fetch.
   */
  where: Prisma.ClientAdApprovalWhereUniqueInput
}

/**
 * ClientAdApproval findFirst
 */
export type ClientAdApprovalFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAdApproval
   */
  select?: Prisma.ClientAdApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAdApproval
   */
  omit?: Prisma.ClientAdApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAdApprovalInclude<ExtArgs> | null
  /**
   * Filter, which ClientAdApproval to fetch.
   */
  where?: Prisma.ClientAdApprovalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientAdApprovals to fetch.
   */
  orderBy?: Prisma.ClientAdApprovalOrderByWithRelationInput | Prisma.ClientAdApprovalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClientAdApprovals.
   */
  cursor?: Prisma.ClientAdApprovalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientAdApprovals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientAdApprovals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClientAdApprovals.
   */
  distinct?: Prisma.ClientAdApprovalScalarFieldEnum | Prisma.ClientAdApprovalScalarFieldEnum[]
}

/**
 * ClientAdApproval findFirstOrThrow
 */
export type ClientAdApprovalFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAdApproval
   */
  select?: Prisma.ClientAdApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAdApproval
   */
  omit?: Prisma.ClientAdApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAdApprovalInclude<ExtArgs> | null
  /**
   * Filter, which ClientAdApproval to fetch.
   */
  where?: Prisma.ClientAdApprovalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientAdApprovals to fetch.
   */
  orderBy?: Prisma.ClientAdApprovalOrderByWithRelationInput | Prisma.ClientAdApprovalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClientAdApprovals.
   */
  cursor?: Prisma.ClientAdApprovalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientAdApprovals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientAdApprovals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClientAdApprovals.
   */
  distinct?: Prisma.ClientAdApprovalScalarFieldEnum | Prisma.ClientAdApprovalScalarFieldEnum[]
}

/**
 * ClientAdApproval findMany
 */
export type ClientAdApprovalFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAdApproval
   */
  select?: Prisma.ClientAdApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAdApproval
   */
  omit?: Prisma.ClientAdApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAdApprovalInclude<ExtArgs> | null
  /**
   * Filter, which ClientAdApprovals to fetch.
   */
  where?: Prisma.ClientAdApprovalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientAdApprovals to fetch.
   */
  orderBy?: Prisma.ClientAdApprovalOrderByWithRelationInput | Prisma.ClientAdApprovalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ClientAdApprovals.
   */
  cursor?: Prisma.ClientAdApprovalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientAdApprovals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientAdApprovals.
   */
  skip?: number
  distinct?: Prisma.ClientAdApprovalScalarFieldEnum | Prisma.ClientAdApprovalScalarFieldEnum[]
}

/**
 * ClientAdApproval create
 */
export type ClientAdApprovalCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAdApproval
   */
  select?: Prisma.ClientAdApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAdApproval
   */
  omit?: Prisma.ClientAdApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAdApprovalInclude<ExtArgs> | null
  /**
   * The data needed to create a ClientAdApproval.
   */
  data: Prisma.XOR<Prisma.ClientAdApprovalCreateInput, Prisma.ClientAdApprovalUncheckedCreateInput>
}

/**
 * ClientAdApproval createMany
 */
export type ClientAdApprovalCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ClientAdApprovals.
   */
  data: Prisma.ClientAdApprovalCreateManyInput | Prisma.ClientAdApprovalCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ClientAdApproval createManyAndReturn
 */
export type ClientAdApprovalCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAdApproval
   */
  select?: Prisma.ClientAdApprovalSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAdApproval
   */
  omit?: Prisma.ClientAdApprovalOmit<ExtArgs> | null
  /**
   * The data used to create many ClientAdApprovals.
   */
  data: Prisma.ClientAdApprovalCreateManyInput | Prisma.ClientAdApprovalCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAdApprovalIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ClientAdApproval update
 */
export type ClientAdApprovalUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAdApproval
   */
  select?: Prisma.ClientAdApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAdApproval
   */
  omit?: Prisma.ClientAdApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAdApprovalInclude<ExtArgs> | null
  /**
   * The data needed to update a ClientAdApproval.
   */
  data: Prisma.XOR<Prisma.ClientAdApprovalUpdateInput, Prisma.ClientAdApprovalUncheckedUpdateInput>
  /**
   * Choose, which ClientAdApproval to update.
   */
  where: Prisma.ClientAdApprovalWhereUniqueInput
}

/**
 * ClientAdApproval updateMany
 */
export type ClientAdApprovalUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ClientAdApprovals.
   */
  data: Prisma.XOR<Prisma.ClientAdApprovalUpdateManyMutationInput, Prisma.ClientAdApprovalUncheckedUpdateManyInput>
  /**
   * Filter which ClientAdApprovals to update
   */
  where?: Prisma.ClientAdApprovalWhereInput
  /**
   * Limit how many ClientAdApprovals to update.
   */
  limit?: number
}

/**
 * ClientAdApproval updateManyAndReturn
 */
export type ClientAdApprovalUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAdApproval
   */
  select?: Prisma.ClientAdApprovalSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAdApproval
   */
  omit?: Prisma.ClientAdApprovalOmit<ExtArgs> | null
  /**
   * The data used to update ClientAdApprovals.
   */
  data: Prisma.XOR<Prisma.ClientAdApprovalUpdateManyMutationInput, Prisma.ClientAdApprovalUncheckedUpdateManyInput>
  /**
   * Filter which ClientAdApprovals to update
   */
  where?: Prisma.ClientAdApprovalWhereInput
  /**
   * Limit how many ClientAdApprovals to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAdApprovalIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ClientAdApproval upsert
 */
export type ClientAdApprovalUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAdApproval
   */
  select?: Prisma.ClientAdApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAdApproval
   */
  omit?: Prisma.ClientAdApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAdApprovalInclude<ExtArgs> | null
  /**
   * The filter to search for the ClientAdApproval to update in case it exists.
   */
  where: Prisma.ClientAdApprovalWhereUniqueInput
  /**
   * In case the ClientAdApproval found by the `where` argument doesn't exist, create a new ClientAdApproval with this data.
   */
  create: Prisma.XOR<Prisma.ClientAdApprovalCreateInput, Prisma.ClientAdApprovalUncheckedCreateInput>
  /**
   * In case the ClientAdApproval was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClientAdApprovalUpdateInput, Prisma.ClientAdApprovalUncheckedUpdateInput>
}

/**
 * ClientAdApproval delete
 */
export type ClientAdApprovalDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAdApproval
   */
  select?: Prisma.ClientAdApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAdApproval
   */
  omit?: Prisma.ClientAdApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAdApprovalInclude<ExtArgs> | null
  /**
   * Filter which ClientAdApproval to delete.
   */
  where: Prisma.ClientAdApprovalWhereUniqueInput
}

/**
 * ClientAdApproval deleteMany
 */
export type ClientAdApprovalDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClientAdApprovals to delete
   */
  where?: Prisma.ClientAdApprovalWhereInput
  /**
   * Limit how many ClientAdApprovals to delete.
   */
  limit?: number
}

/**
 * ClientAdApproval without action
 */
export type ClientAdApprovalDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientAdApproval
   */
  select?: Prisma.ClientAdApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientAdApproval
   */
  omit?: Prisma.ClientAdApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientAdApprovalInclude<ExtArgs> | null
}
