
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ClientMessage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ClientMessage
 * 
 */
export type ClientMessageModel = runtime.Types.Result.DefaultSelection<Prisma.$ClientMessagePayload>

export type AggregateClientMessage = {
  _count: ClientMessageCountAggregateOutputType | null
  _min: ClientMessageMinAggregateOutputType | null
  _max: ClientMessageMaxAggregateOutputType | null
}

export type ClientMessageMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  clientAccountId: string | null
  senderId: string | null
  senderType: string | null
  senderName: string | null
  subject: string | null
  message: string | null
  isRead: boolean | null
  readAt: Date | null
  replyToId: string | null
}

export type ClientMessageMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  clientAccountId: string | null
  senderId: string | null
  senderType: string | null
  senderName: string | null
  subject: string | null
  message: string | null
  isRead: boolean | null
  readAt: Date | null
  replyToId: string | null
}

export type ClientMessageCountAggregateOutputType = {
  id: number
  createdAt: number
  clientAccountId: number
  senderId: number
  senderType: number
  senderName: number
  subject: number
  message: number
  attachments: number
  isRead: number
  readAt: number
  replyToId: number
  _all: number
}


export type ClientMessageMinAggregateInputType = {
  id?: true
  createdAt?: true
  clientAccountId?: true
  senderId?: true
  senderType?: true
  senderName?: true
  subject?: true
  message?: true
  isRead?: true
  readAt?: true
  replyToId?: true
}

export type ClientMessageMaxAggregateInputType = {
  id?: true
  createdAt?: true
  clientAccountId?: true
  senderId?: true
  senderType?: true
  senderName?: true
  subject?: true
  message?: true
  isRead?: true
  readAt?: true
  replyToId?: true
}

export type ClientMessageCountAggregateInputType = {
  id?: true
  createdAt?: true
  clientAccountId?: true
  senderId?: true
  senderType?: true
  senderName?: true
  subject?: true
  message?: true
  attachments?: true
  isRead?: true
  readAt?: true
  replyToId?: true
  _all?: true
}

export type ClientMessageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClientMessage to aggregate.
   */
  where?: Prisma.ClientMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientMessages to fetch.
   */
  orderBy?: Prisma.ClientMessageOrderByWithRelationInput | Prisma.ClientMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ClientMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ClientMessages
  **/
  _count?: true | ClientMessageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ClientMessageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ClientMessageMaxAggregateInputType
}

export type GetClientMessageAggregateType<T extends ClientMessageAggregateArgs> = {
      [P in keyof T & keyof AggregateClientMessage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClientMessage[P]>
    : Prisma.GetScalarType<T[P], AggregateClientMessage[P]>
}




export type ClientMessageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClientMessageWhereInput
  orderBy?: Prisma.ClientMessageOrderByWithAggregationInput | Prisma.ClientMessageOrderByWithAggregationInput[]
  by: Prisma.ClientMessageScalarFieldEnum[] | Prisma.ClientMessageScalarFieldEnum
  having?: Prisma.ClientMessageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ClientMessageCountAggregateInputType | true
  _min?: ClientMessageMinAggregateInputType
  _max?: ClientMessageMaxAggregateInputType
}

export type ClientMessageGroupByOutputType = {
  id: string
  createdAt: Date
  clientAccountId: string
  senderId: string
  senderType: string
  senderName: string
  subject: string | null
  message: string
  attachments: runtime.JsonValue | null
  isRead: boolean
  readAt: Date | null
  replyToId: string | null
  _count: ClientMessageCountAggregateOutputType | null
  _min: ClientMessageMinAggregateOutputType | null
  _max: ClientMessageMaxAggregateOutputType | null
}

type GetClientMessageGroupByPayload<T extends ClientMessageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ClientMessageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ClientMessageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClientMessageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClientMessageGroupByOutputType[P]>
      }
    >
  >



export type ClientMessageWhereInput = {
  AND?: Prisma.ClientMessageWhereInput | Prisma.ClientMessageWhereInput[]
  OR?: Prisma.ClientMessageWhereInput[]
  NOT?: Prisma.ClientMessageWhereInput | Prisma.ClientMessageWhereInput[]
  id?: Prisma.StringFilter<"ClientMessage"> | string
  createdAt?: Prisma.DateTimeFilter<"ClientMessage"> | Date | string
  clientAccountId?: Prisma.StringFilter<"ClientMessage"> | string
  senderId?: Prisma.StringFilter<"ClientMessage"> | string
  senderType?: Prisma.StringFilter<"ClientMessage"> | string
  senderName?: Prisma.StringFilter<"ClientMessage"> | string
  subject?: Prisma.StringNullableFilter<"ClientMessage"> | string | null
  message?: Prisma.StringFilter<"ClientMessage"> | string
  attachments?: Prisma.JsonNullableFilter<"ClientMessage">
  isRead?: Prisma.BoolFilter<"ClientMessage"> | boolean
  readAt?: Prisma.DateTimeNullableFilter<"ClientMessage"> | Date | string | null
  replyToId?: Prisma.StringNullableFilter<"ClientMessage"> | string | null
  ClientAccount?: Prisma.XOR<Prisma.ClientAccountScalarRelationFilter, Prisma.ClientAccountWhereInput>
}

export type ClientMessageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
  senderId?: Prisma.SortOrder
  senderType?: Prisma.SortOrder
  senderName?: Prisma.SortOrder
  subject?: Prisma.SortOrderInput | Prisma.SortOrder
  message?: Prisma.SortOrder
  attachments?: Prisma.SortOrderInput | Prisma.SortOrder
  isRead?: Prisma.SortOrder
  readAt?: Prisma.SortOrderInput | Prisma.SortOrder
  replyToId?: Prisma.SortOrderInput | Prisma.SortOrder
  ClientAccount?: Prisma.ClientAccountOrderByWithRelationInput
}

export type ClientMessageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ClientMessageWhereInput | Prisma.ClientMessageWhereInput[]
  OR?: Prisma.ClientMessageWhereInput[]
  NOT?: Prisma.ClientMessageWhereInput | Prisma.ClientMessageWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"ClientMessage"> | Date | string
  clientAccountId?: Prisma.StringFilter<"ClientMessage"> | string
  senderId?: Prisma.StringFilter<"ClientMessage"> | string
  senderType?: Prisma.StringFilter<"ClientMessage"> | string
  senderName?: Prisma.StringFilter<"ClientMessage"> | string
  subject?: Prisma.StringNullableFilter<"ClientMessage"> | string | null
  message?: Prisma.StringFilter<"ClientMessage"> | string
  attachments?: Prisma.JsonNullableFilter<"ClientMessage">
  isRead?: Prisma.BoolFilter<"ClientMessage"> | boolean
  readAt?: Prisma.DateTimeNullableFilter<"ClientMessage"> | Date | string | null
  replyToId?: Prisma.StringNullableFilter<"ClientMessage"> | string | null
  ClientAccount?: Prisma.XOR<Prisma.ClientAccountScalarRelationFilter, Prisma.ClientAccountWhereInput>
}, "id">

export type ClientMessageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
  senderId?: Prisma.SortOrder
  senderType?: Prisma.SortOrder
  senderName?: Prisma.SortOrder
  subject?: Prisma.SortOrderInput | Prisma.SortOrder
  message?: Prisma.SortOrder
  attachments?: Prisma.SortOrderInput | Prisma.SortOrder
  isRead?: Prisma.SortOrder
  readAt?: Prisma.SortOrderInput | Prisma.SortOrder
  replyToId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ClientMessageCountOrderByAggregateInput
  _max?: Prisma.ClientMessageMaxOrderByAggregateInput
  _min?: Prisma.ClientMessageMinOrderByAggregateInput
}

export type ClientMessageScalarWhereWithAggregatesInput = {
  AND?: Prisma.ClientMessageScalarWhereWithAggregatesInput | Prisma.ClientMessageScalarWhereWithAggregatesInput[]
  OR?: Prisma.ClientMessageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ClientMessageScalarWhereWithAggregatesInput | Prisma.ClientMessageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ClientMessage"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ClientMessage"> | Date | string
  clientAccountId?: Prisma.StringWithAggregatesFilter<"ClientMessage"> | string
  senderId?: Prisma.StringWithAggregatesFilter<"ClientMessage"> | string
  senderType?: Prisma.StringWithAggregatesFilter<"ClientMessage"> | string
  senderName?: Prisma.StringWithAggregatesFilter<"ClientMessage"> | string
  subject?: Prisma.StringNullableWithAggregatesFilter<"ClientMessage"> | string | null
  message?: Prisma.StringWithAggregatesFilter<"ClientMessage"> | string
  attachments?: Prisma.JsonNullableWithAggregatesFilter<"ClientMessage">
  isRead?: Prisma.BoolWithAggregatesFilter<"ClientMessage"> | boolean
  readAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ClientMessage"> | Date | string | null
  replyToId?: Prisma.StringNullableWithAggregatesFilter<"ClientMessage"> | string | null
}

export type ClientMessageCreateInput = {
  id: string
  createdAt?: Date | string
  senderId: string
  senderType: string
  senderName: string
  subject?: string | null
  message: string
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isRead?: boolean
  readAt?: Date | string | null
  replyToId?: string | null
  ClientAccount: Prisma.ClientAccountCreateNestedOneWithoutClientMessageInput
}

export type ClientMessageUncheckedCreateInput = {
  id: string
  createdAt?: Date | string
  clientAccountId: string
  senderId: string
  senderType: string
  senderName: string
  subject?: string | null
  message: string
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isRead?: boolean
  readAt?: Date | string | null
  replyToId?: string | null
}

export type ClientMessageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  senderId?: Prisma.StringFieldUpdateOperationsInput | string
  senderType?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isRead?: Prisma.BoolFieldUpdateOperationsInput | boolean
  readAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ClientAccount?: Prisma.ClientAccountUpdateOneRequiredWithoutClientMessageNestedInput
}

export type ClientMessageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  senderId?: Prisma.StringFieldUpdateOperationsInput | string
  senderType?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isRead?: Prisma.BoolFieldUpdateOperationsInput | boolean
  readAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ClientMessageCreateManyInput = {
  id: string
  createdAt?: Date | string
  clientAccountId: string
  senderId: string
  senderType: string
  senderName: string
  subject?: string | null
  message: string
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isRead?: boolean
  readAt?: Date | string | null
  replyToId?: string | null
}

export type ClientMessageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  senderId?: Prisma.StringFieldUpdateOperationsInput | string
  senderType?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isRead?: Prisma.BoolFieldUpdateOperationsInput | boolean
  readAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ClientMessageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  senderId?: Prisma.StringFieldUpdateOperationsInput | string
  senderType?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isRead?: Prisma.BoolFieldUpdateOperationsInput | boolean
  readAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ClientMessageListRelationFilter = {
  every?: Prisma.ClientMessageWhereInput
  some?: Prisma.ClientMessageWhereInput
  none?: Prisma.ClientMessageWhereInput
}

export type ClientMessageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ClientMessageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
  senderId?: Prisma.SortOrder
  senderType?: Prisma.SortOrder
  senderName?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  message?: Prisma.SortOrder
  attachments?: Prisma.SortOrder
  isRead?: Prisma.SortOrder
  readAt?: Prisma.SortOrder
  replyToId?: Prisma.SortOrder
}

export type ClientMessageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
  senderId?: Prisma.SortOrder
  senderType?: Prisma.SortOrder
  senderName?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  message?: Prisma.SortOrder
  isRead?: Prisma.SortOrder
  readAt?: Prisma.SortOrder
  replyToId?: Prisma.SortOrder
}

export type ClientMessageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
  senderId?: Prisma.SortOrder
  senderType?: Prisma.SortOrder
  senderName?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  message?: Prisma.SortOrder
  isRead?: Prisma.SortOrder
  readAt?: Prisma.SortOrder
  replyToId?: Prisma.SortOrder
}

export type ClientMessageCreateNestedManyWithoutClientAccountInput = {
  create?: Prisma.XOR<Prisma.ClientMessageCreateWithoutClientAccountInput, Prisma.ClientMessageUncheckedCreateWithoutClientAccountInput> | Prisma.ClientMessageCreateWithoutClientAccountInput[] | Prisma.ClientMessageUncheckedCreateWithoutClientAccountInput[]
  connectOrCreate?: Prisma.ClientMessageCreateOrConnectWithoutClientAccountInput | Prisma.ClientMessageCreateOrConnectWithoutClientAccountInput[]
  createMany?: Prisma.ClientMessageCreateManyClientAccountInputEnvelope
  connect?: Prisma.ClientMessageWhereUniqueInput | Prisma.ClientMessageWhereUniqueInput[]
}

export type ClientMessageUncheckedCreateNestedManyWithoutClientAccountInput = {
  create?: Prisma.XOR<Prisma.ClientMessageCreateWithoutClientAccountInput, Prisma.ClientMessageUncheckedCreateWithoutClientAccountInput> | Prisma.ClientMessageCreateWithoutClientAccountInput[] | Prisma.ClientMessageUncheckedCreateWithoutClientAccountInput[]
  connectOrCreate?: Prisma.ClientMessageCreateOrConnectWithoutClientAccountInput | Prisma.ClientMessageCreateOrConnectWithoutClientAccountInput[]
  createMany?: Prisma.ClientMessageCreateManyClientAccountInputEnvelope
  connect?: Prisma.ClientMessageWhereUniqueInput | Prisma.ClientMessageWhereUniqueInput[]
}

export type ClientMessageUpdateManyWithoutClientAccountNestedInput = {
  create?: Prisma.XOR<Prisma.ClientMessageCreateWithoutClientAccountInput, Prisma.ClientMessageUncheckedCreateWithoutClientAccountInput> | Prisma.ClientMessageCreateWithoutClientAccountInput[] | Prisma.ClientMessageUncheckedCreateWithoutClientAccountInput[]
  connectOrCreate?: Prisma.ClientMessageCreateOrConnectWithoutClientAccountInput | Prisma.ClientMessageCreateOrConnectWithoutClientAccountInput[]
  upsert?: Prisma.ClientMessageUpsertWithWhereUniqueWithoutClientAccountInput | Prisma.ClientMessageUpsertWithWhereUniqueWithoutClientAccountInput[]
  createMany?: Prisma.ClientMessageCreateManyClientAccountInputEnvelope
  set?: Prisma.ClientMessageWhereUniqueInput | Prisma.ClientMessageWhereUniqueInput[]
  disconnect?: Prisma.ClientMessageWhereUniqueInput | Prisma.ClientMessageWhereUniqueInput[]
  delete?: Prisma.ClientMessageWhereUniqueInput | Prisma.ClientMessageWhereUniqueInput[]
  connect?: Prisma.ClientMessageWhereUniqueInput | Prisma.ClientMessageWhereUniqueInput[]
  update?: Prisma.ClientMessageUpdateWithWhereUniqueWithoutClientAccountInput | Prisma.ClientMessageUpdateWithWhereUniqueWithoutClientAccountInput[]
  updateMany?: Prisma.ClientMessageUpdateManyWithWhereWithoutClientAccountInput | Prisma.ClientMessageUpdateManyWithWhereWithoutClientAccountInput[]
  deleteMany?: Prisma.ClientMessageScalarWhereInput | Prisma.ClientMessageScalarWhereInput[]
}

export type ClientMessageUncheckedUpdateManyWithoutClientAccountNestedInput = {
  create?: Prisma.XOR<Prisma.ClientMessageCreateWithoutClientAccountInput, Prisma.ClientMessageUncheckedCreateWithoutClientAccountInput> | Prisma.ClientMessageCreateWithoutClientAccountInput[] | Prisma.ClientMessageUncheckedCreateWithoutClientAccountInput[]
  connectOrCreate?: Prisma.ClientMessageCreateOrConnectWithoutClientAccountInput | Prisma.ClientMessageCreateOrConnectWithoutClientAccountInput[]
  upsert?: Prisma.ClientMessageUpsertWithWhereUniqueWithoutClientAccountInput | Prisma.ClientMessageUpsertWithWhereUniqueWithoutClientAccountInput[]
  createMany?: Prisma.ClientMessageCreateManyClientAccountInputEnvelope
  set?: Prisma.ClientMessageWhereUniqueInput | Prisma.ClientMessageWhereUniqueInput[]
  disconnect?: Prisma.ClientMessageWhereUniqueInput | Prisma.ClientMessageWhereUniqueInput[]
  delete?: Prisma.ClientMessageWhereUniqueInput | Prisma.ClientMessageWhereUniqueInput[]
  connect?: Prisma.ClientMessageWhereUniqueInput | Prisma.ClientMessageWhereUniqueInput[]
  update?: Prisma.ClientMessageUpdateWithWhereUniqueWithoutClientAccountInput | Prisma.ClientMessageUpdateWithWhereUniqueWithoutClientAccountInput[]
  updateMany?: Prisma.ClientMessageUpdateManyWithWhereWithoutClientAccountInput | Prisma.ClientMessageUpdateManyWithWhereWithoutClientAccountInput[]
  deleteMany?: Prisma.ClientMessageScalarWhereInput | Prisma.ClientMessageScalarWhereInput[]
}

export type ClientMessageCreateWithoutClientAccountInput = {
  id: string
  createdAt?: Date | string
  senderId: string
  senderType: string
  senderName: string
  subject?: string | null
  message: string
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isRead?: boolean
  readAt?: Date | string | null
  replyToId?: string | null
}

export type ClientMessageUncheckedCreateWithoutClientAccountInput = {
  id: string
  createdAt?: Date | string
  senderId: string
  senderType: string
  senderName: string
  subject?: string | null
  message: string
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isRead?: boolean
  readAt?: Date | string | null
  replyToId?: string | null
}

export type ClientMessageCreateOrConnectWithoutClientAccountInput = {
  where: Prisma.ClientMessageWhereUniqueInput
  create: Prisma.XOR<Prisma.ClientMessageCreateWithoutClientAccountInput, Prisma.ClientMessageUncheckedCreateWithoutClientAccountInput>
}

export type ClientMessageCreateManyClientAccountInputEnvelope = {
  data: Prisma.ClientMessageCreateManyClientAccountInput | Prisma.ClientMessageCreateManyClientAccountInput[]
  skipDuplicates?: boolean
}

export type ClientMessageUpsertWithWhereUniqueWithoutClientAccountInput = {
  where: Prisma.ClientMessageWhereUniqueInput
  update: Prisma.XOR<Prisma.ClientMessageUpdateWithoutClientAccountInput, Prisma.ClientMessageUncheckedUpdateWithoutClientAccountInput>
  create: Prisma.XOR<Prisma.ClientMessageCreateWithoutClientAccountInput, Prisma.ClientMessageUncheckedCreateWithoutClientAccountInput>
}

export type ClientMessageUpdateWithWhereUniqueWithoutClientAccountInput = {
  where: Prisma.ClientMessageWhereUniqueInput
  data: Prisma.XOR<Prisma.ClientMessageUpdateWithoutClientAccountInput, Prisma.ClientMessageUncheckedUpdateWithoutClientAccountInput>
}

export type ClientMessageUpdateManyWithWhereWithoutClientAccountInput = {
  where: Prisma.ClientMessageScalarWhereInput
  data: Prisma.XOR<Prisma.ClientMessageUpdateManyMutationInput, Prisma.ClientMessageUncheckedUpdateManyWithoutClientAccountInput>
}

export type ClientMessageScalarWhereInput = {
  AND?: Prisma.ClientMessageScalarWhereInput | Prisma.ClientMessageScalarWhereInput[]
  OR?: Prisma.ClientMessageScalarWhereInput[]
  NOT?: Prisma.ClientMessageScalarWhereInput | Prisma.ClientMessageScalarWhereInput[]
  id?: Prisma.StringFilter<"ClientMessage"> | string
  createdAt?: Prisma.DateTimeFilter<"ClientMessage"> | Date | string
  clientAccountId?: Prisma.StringFilter<"ClientMessage"> | string
  senderId?: Prisma.StringFilter<"ClientMessage"> | string
  senderType?: Prisma.StringFilter<"ClientMessage"> | string
  senderName?: Prisma.StringFilter<"ClientMessage"> | string
  subject?: Prisma.StringNullableFilter<"ClientMessage"> | string | null
  message?: Prisma.StringFilter<"ClientMessage"> | string
  attachments?: Prisma.JsonNullableFilter<"ClientMessage">
  isRead?: Prisma.BoolFilter<"ClientMessage"> | boolean
  readAt?: Prisma.DateTimeNullableFilter<"ClientMessage"> | Date | string | null
  replyToId?: Prisma.StringNullableFilter<"ClientMessage"> | string | null
}

export type ClientMessageCreateManyClientAccountInput = {
  id: string
  createdAt?: Date | string
  senderId: string
  senderType: string
  senderName: string
  subject?: string | null
  message: string
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isRead?: boolean
  readAt?: Date | string | null
  replyToId?: string | null
}

export type ClientMessageUpdateWithoutClientAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  senderId?: Prisma.StringFieldUpdateOperationsInput | string
  senderType?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isRead?: Prisma.BoolFieldUpdateOperationsInput | boolean
  readAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ClientMessageUncheckedUpdateWithoutClientAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  senderId?: Prisma.StringFieldUpdateOperationsInput | string
  senderType?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isRead?: Prisma.BoolFieldUpdateOperationsInput | boolean
  readAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ClientMessageUncheckedUpdateManyWithoutClientAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  senderId?: Prisma.StringFieldUpdateOperationsInput | string
  senderType?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isRead?: Prisma.BoolFieldUpdateOperationsInput | boolean
  readAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  replyToId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type ClientMessageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  clientAccountId?: boolean
  senderId?: boolean
  senderType?: boolean
  senderName?: boolean
  subject?: boolean
  message?: boolean
  attachments?: boolean
  isRead?: boolean
  readAt?: boolean
  replyToId?: boolean
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clientMessage"]>

export type ClientMessageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  clientAccountId?: boolean
  senderId?: boolean
  senderType?: boolean
  senderName?: boolean
  subject?: boolean
  message?: boolean
  attachments?: boolean
  isRead?: boolean
  readAt?: boolean
  replyToId?: boolean
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clientMessage"]>

export type ClientMessageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  clientAccountId?: boolean
  senderId?: boolean
  senderType?: boolean
  senderName?: boolean
  subject?: boolean
  message?: boolean
  attachments?: boolean
  isRead?: boolean
  readAt?: boolean
  replyToId?: boolean
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clientMessage"]>

export type ClientMessageSelectScalar = {
  id?: boolean
  createdAt?: boolean
  clientAccountId?: boolean
  senderId?: boolean
  senderType?: boolean
  senderName?: boolean
  subject?: boolean
  message?: boolean
  attachments?: boolean
  isRead?: boolean
  readAt?: boolean
  replyToId?: boolean
}

export type ClientMessageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "clientAccountId" | "senderId" | "senderType" | "senderName" | "subject" | "message" | "attachments" | "isRead" | "readAt" | "replyToId", ExtArgs["result"]["clientMessage"]>
export type ClientMessageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}
export type ClientMessageIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}
export type ClientMessageIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}

export type $ClientMessagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ClientMessage"
  objects: {
    ClientAccount: Prisma.$ClientAccountPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    clientAccountId: string
    senderId: string
    senderType: string
    senderName: string
    subject: string | null
    message: string
    attachments: runtime.JsonValue | null
    isRead: boolean
    readAt: Date | null
    replyToId: string | null
  }, ExtArgs["result"]["clientMessage"]>
  composites: {}
}

export type ClientMessageGetPayload<S extends boolean | null | undefined | ClientMessageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ClientMessagePayload, S>

export type ClientMessageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ClientMessageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ClientMessageCountAggregateInputType | true
  }

export interface ClientMessageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ClientMessage'], meta: { name: 'ClientMessage' } }
  /**
   * Find zero or one ClientMessage that matches the filter.
   * @param {ClientMessageFindUniqueArgs} args - Arguments to find a ClientMessage
   * @example
   * // Get one ClientMessage
   * const clientMessage = await prisma.clientMessage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClientMessageFindUniqueArgs>(args: Prisma.SelectSubset<T, ClientMessageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ClientMessageClient<runtime.Types.Result.GetResult<Prisma.$ClientMessagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ClientMessage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClientMessageFindUniqueOrThrowArgs} args - Arguments to find a ClientMessage
   * @example
   * // Get one ClientMessage
   * const clientMessage = await prisma.clientMessage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClientMessageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ClientMessageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClientMessageClient<runtime.Types.Result.GetResult<Prisma.$ClientMessagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClientMessage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientMessageFindFirstArgs} args - Arguments to find a ClientMessage
   * @example
   * // Get one ClientMessage
   * const clientMessage = await prisma.clientMessage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClientMessageFindFirstArgs>(args?: Prisma.SelectSubset<T, ClientMessageFindFirstArgs<ExtArgs>>): Prisma.Prisma__ClientMessageClient<runtime.Types.Result.GetResult<Prisma.$ClientMessagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClientMessage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientMessageFindFirstOrThrowArgs} args - Arguments to find a ClientMessage
   * @example
   * // Get one ClientMessage
   * const clientMessage = await prisma.clientMessage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClientMessageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ClientMessageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClientMessageClient<runtime.Types.Result.GetResult<Prisma.$ClientMessagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ClientMessages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientMessageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ClientMessages
   * const clientMessages = await prisma.clientMessage.findMany()
   * 
   * // Get first 10 ClientMessages
   * const clientMessages = await prisma.clientMessage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const clientMessageWithIdOnly = await prisma.clientMessage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ClientMessageFindManyArgs>(args?: Prisma.SelectSubset<T, ClientMessageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientMessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ClientMessage.
   * @param {ClientMessageCreateArgs} args - Arguments to create a ClientMessage.
   * @example
   * // Create one ClientMessage
   * const ClientMessage = await prisma.clientMessage.create({
   *   data: {
   *     // ... data to create a ClientMessage
   *   }
   * })
   * 
   */
  create<T extends ClientMessageCreateArgs>(args: Prisma.SelectSubset<T, ClientMessageCreateArgs<ExtArgs>>): Prisma.Prisma__ClientMessageClient<runtime.Types.Result.GetResult<Prisma.$ClientMessagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ClientMessages.
   * @param {ClientMessageCreateManyArgs} args - Arguments to create many ClientMessages.
   * @example
   * // Create many ClientMessages
   * const clientMessage = await prisma.clientMessage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ClientMessageCreateManyArgs>(args?: Prisma.SelectSubset<T, ClientMessageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ClientMessages and returns the data saved in the database.
   * @param {ClientMessageCreateManyAndReturnArgs} args - Arguments to create many ClientMessages.
   * @example
   * // Create many ClientMessages
   * const clientMessage = await prisma.clientMessage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ClientMessages and only return the `id`
   * const clientMessageWithIdOnly = await prisma.clientMessage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ClientMessageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ClientMessageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientMessagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ClientMessage.
   * @param {ClientMessageDeleteArgs} args - Arguments to delete one ClientMessage.
   * @example
   * // Delete one ClientMessage
   * const ClientMessage = await prisma.clientMessage.delete({
   *   where: {
   *     // ... filter to delete one ClientMessage
   *   }
   * })
   * 
   */
  delete<T extends ClientMessageDeleteArgs>(args: Prisma.SelectSubset<T, ClientMessageDeleteArgs<ExtArgs>>): Prisma.Prisma__ClientMessageClient<runtime.Types.Result.GetResult<Prisma.$ClientMessagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ClientMessage.
   * @param {ClientMessageUpdateArgs} args - Arguments to update one ClientMessage.
   * @example
   * // Update one ClientMessage
   * const clientMessage = await prisma.clientMessage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ClientMessageUpdateArgs>(args: Prisma.SelectSubset<T, ClientMessageUpdateArgs<ExtArgs>>): Prisma.Prisma__ClientMessageClient<runtime.Types.Result.GetResult<Prisma.$ClientMessagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ClientMessages.
   * @param {ClientMessageDeleteManyArgs} args - Arguments to filter ClientMessages to delete.
   * @example
   * // Delete a few ClientMessages
   * const { count } = await prisma.clientMessage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ClientMessageDeleteManyArgs>(args?: Prisma.SelectSubset<T, ClientMessageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ClientMessages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientMessageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ClientMessages
   * const clientMessage = await prisma.clientMessage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ClientMessageUpdateManyArgs>(args: Prisma.SelectSubset<T, ClientMessageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ClientMessages and returns the data updated in the database.
   * @param {ClientMessageUpdateManyAndReturnArgs} args - Arguments to update many ClientMessages.
   * @example
   * // Update many ClientMessages
   * const clientMessage = await prisma.clientMessage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ClientMessages and only return the `id`
   * const clientMessageWithIdOnly = await prisma.clientMessage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ClientMessageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ClientMessageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientMessagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ClientMessage.
   * @param {ClientMessageUpsertArgs} args - Arguments to update or create a ClientMessage.
   * @example
   * // Update or create a ClientMessage
   * const clientMessage = await prisma.clientMessage.upsert({
   *   create: {
   *     // ... data to create a ClientMessage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ClientMessage we want to update
   *   }
   * })
   */
  upsert<T extends ClientMessageUpsertArgs>(args: Prisma.SelectSubset<T, ClientMessageUpsertArgs<ExtArgs>>): Prisma.Prisma__ClientMessageClient<runtime.Types.Result.GetResult<Prisma.$ClientMessagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ClientMessages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientMessageCountArgs} args - Arguments to filter ClientMessages to count.
   * @example
   * // Count the number of ClientMessages
   * const count = await prisma.clientMessage.count({
   *   where: {
   *     // ... the filter for the ClientMessages we want to count
   *   }
   * })
  **/
  count<T extends ClientMessageCountArgs>(
    args?: Prisma.Subset<T, ClientMessageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClientMessageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ClientMessage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientMessageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ClientMessageAggregateArgs>(args: Prisma.Subset<T, ClientMessageAggregateArgs>): Prisma.PrismaPromise<GetClientMessageAggregateType<T>>

  /**
   * Group by ClientMessage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientMessageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ClientMessageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ClientMessageGroupByArgs['orderBy'] }
      : { orderBy?: ClientMessageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ClientMessageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClientMessageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ClientMessage model
 */
readonly fields: ClientMessageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ClientMessage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClientMessageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ClientAccount<T extends Prisma.ClientAccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClientAccountDefaultArgs<ExtArgs>>): Prisma.Prisma__ClientAccountClient<runtime.Types.Result.GetResult<Prisma.$ClientAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ClientMessage model
 */
export interface ClientMessageFieldRefs {
  readonly id: Prisma.FieldRef<"ClientMessage", 'String'>
  readonly createdAt: Prisma.FieldRef<"ClientMessage", 'DateTime'>
  readonly clientAccountId: Prisma.FieldRef<"ClientMessage", 'String'>
  readonly senderId: Prisma.FieldRef<"ClientMessage", 'String'>
  readonly senderType: Prisma.FieldRef<"ClientMessage", 'String'>
  readonly senderName: Prisma.FieldRef<"ClientMessage", 'String'>
  readonly subject: Prisma.FieldRef<"ClientMessage", 'String'>
  readonly message: Prisma.FieldRef<"ClientMessage", 'String'>
  readonly attachments: Prisma.FieldRef<"ClientMessage", 'Json'>
  readonly isRead: Prisma.FieldRef<"ClientMessage", 'Boolean'>
  readonly readAt: Prisma.FieldRef<"ClientMessage", 'DateTime'>
  readonly replyToId: Prisma.FieldRef<"ClientMessage", 'String'>
}
    

// Custom InputTypes
/**
 * ClientMessage findUnique
 */
export type ClientMessageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientMessage
   */
  select?: Prisma.ClientMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientMessage
   */
  omit?: Prisma.ClientMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientMessageInclude<ExtArgs> | null
  /**
   * Filter, which ClientMessage to fetch.
   */
  where: Prisma.ClientMessageWhereUniqueInput
}

/**
 * ClientMessage findUniqueOrThrow
 */
export type ClientMessageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientMessage
   */
  select?: Prisma.ClientMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientMessage
   */
  omit?: Prisma.ClientMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientMessageInclude<ExtArgs> | null
  /**
   * Filter, which ClientMessage to fetch.
   */
  where: Prisma.ClientMessageWhereUniqueInput
}

/**
 * ClientMessage findFirst
 */
export type ClientMessageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientMessage
   */
  select?: Prisma.ClientMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientMessage
   */
  omit?: Prisma.ClientMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientMessageInclude<ExtArgs> | null
  /**
   * Filter, which ClientMessage to fetch.
   */
  where?: Prisma.ClientMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientMessages to fetch.
   */
  orderBy?: Prisma.ClientMessageOrderByWithRelationInput | Prisma.ClientMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClientMessages.
   */
  cursor?: Prisma.ClientMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClientMessages.
   */
  distinct?: Prisma.ClientMessageScalarFieldEnum | Prisma.ClientMessageScalarFieldEnum[]
}

/**
 * ClientMessage findFirstOrThrow
 */
export type ClientMessageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientMessage
   */
  select?: Prisma.ClientMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientMessage
   */
  omit?: Prisma.ClientMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientMessageInclude<ExtArgs> | null
  /**
   * Filter, which ClientMessage to fetch.
   */
  where?: Prisma.ClientMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientMessages to fetch.
   */
  orderBy?: Prisma.ClientMessageOrderByWithRelationInput | Prisma.ClientMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClientMessages.
   */
  cursor?: Prisma.ClientMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClientMessages.
   */
  distinct?: Prisma.ClientMessageScalarFieldEnum | Prisma.ClientMessageScalarFieldEnum[]
}

/**
 * ClientMessage findMany
 */
export type ClientMessageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientMessage
   */
  select?: Prisma.ClientMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientMessage
   */
  omit?: Prisma.ClientMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientMessageInclude<ExtArgs> | null
  /**
   * Filter, which ClientMessages to fetch.
   */
  where?: Prisma.ClientMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientMessages to fetch.
   */
  orderBy?: Prisma.ClientMessageOrderByWithRelationInput | Prisma.ClientMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ClientMessages.
   */
  cursor?: Prisma.ClientMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientMessages.
   */
  skip?: number
  distinct?: Prisma.ClientMessageScalarFieldEnum | Prisma.ClientMessageScalarFieldEnum[]
}

/**
 * ClientMessage create
 */
export type ClientMessageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientMessage
   */
  select?: Prisma.ClientMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientMessage
   */
  omit?: Prisma.ClientMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientMessageInclude<ExtArgs> | null
  /**
   * The data needed to create a ClientMessage.
   */
  data: Prisma.XOR<Prisma.ClientMessageCreateInput, Prisma.ClientMessageUncheckedCreateInput>
}

/**
 * ClientMessage createMany
 */
export type ClientMessageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ClientMessages.
   */
  data: Prisma.ClientMessageCreateManyInput | Prisma.ClientMessageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ClientMessage createManyAndReturn
 */
export type ClientMessageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientMessage
   */
  select?: Prisma.ClientMessageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ClientMessage
   */
  omit?: Prisma.ClientMessageOmit<ExtArgs> | null
  /**
   * The data used to create many ClientMessages.
   */
  data: Prisma.ClientMessageCreateManyInput | Prisma.ClientMessageCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientMessageIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ClientMessage update
 */
export type ClientMessageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientMessage
   */
  select?: Prisma.ClientMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientMessage
   */
  omit?: Prisma.ClientMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientMessageInclude<ExtArgs> | null
  /**
   * The data needed to update a ClientMessage.
   */
  data: Prisma.XOR<Prisma.ClientMessageUpdateInput, Prisma.ClientMessageUncheckedUpdateInput>
  /**
   * Choose, which ClientMessage to update.
   */
  where: Prisma.ClientMessageWhereUniqueInput
}

/**
 * ClientMessage updateMany
 */
export type ClientMessageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ClientMessages.
   */
  data: Prisma.XOR<Prisma.ClientMessageUpdateManyMutationInput, Prisma.ClientMessageUncheckedUpdateManyInput>
  /**
   * Filter which ClientMessages to update
   */
  where?: Prisma.ClientMessageWhereInput
  /**
   * Limit how many ClientMessages to update.
   */
  limit?: number
}

/**
 * ClientMessage updateManyAndReturn
 */
export type ClientMessageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientMessage
   */
  select?: Prisma.ClientMessageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ClientMessage
   */
  omit?: Prisma.ClientMessageOmit<ExtArgs> | null
  /**
   * The data used to update ClientMessages.
   */
  data: Prisma.XOR<Prisma.ClientMessageUpdateManyMutationInput, Prisma.ClientMessageUncheckedUpdateManyInput>
  /**
   * Filter which ClientMessages to update
   */
  where?: Prisma.ClientMessageWhereInput
  /**
   * Limit how many ClientMessages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientMessageIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ClientMessage upsert
 */
export type ClientMessageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientMessage
   */
  select?: Prisma.ClientMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientMessage
   */
  omit?: Prisma.ClientMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientMessageInclude<ExtArgs> | null
  /**
   * The filter to search for the ClientMessage to update in case it exists.
   */
  where: Prisma.ClientMessageWhereUniqueInput
  /**
   * In case the ClientMessage found by the `where` argument doesn't exist, create a new ClientMessage with this data.
   */
  create: Prisma.XOR<Prisma.ClientMessageCreateInput, Prisma.ClientMessageUncheckedCreateInput>
  /**
   * In case the ClientMessage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClientMessageUpdateInput, Prisma.ClientMessageUncheckedUpdateInput>
}

/**
 * ClientMessage delete
 */
export type ClientMessageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientMessage
   */
  select?: Prisma.ClientMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientMessage
   */
  omit?: Prisma.ClientMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientMessageInclude<ExtArgs> | null
  /**
   * Filter which ClientMessage to delete.
   */
  where: Prisma.ClientMessageWhereUniqueInput
}

/**
 * ClientMessage deleteMany
 */
export type ClientMessageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClientMessages to delete
   */
  where?: Prisma.ClientMessageWhereInput
  /**
   * Limit how many ClientMessages to delete.
   */
  limit?: number
}

/**
 * ClientMessage without action
 */
export type ClientMessageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientMessage
   */
  select?: Prisma.ClientMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientMessage
   */
  omit?: Prisma.ClientMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientMessageInclude<ExtArgs> | null
}
