
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ClientProject` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ClientProject
 * 
 */
export type ClientProjectModel = runtime.Types.Result.DefaultSelection<Prisma.$ClientProjectPayload>

export type AggregateClientProject = {
  _count: ClientProjectCountAggregateOutputType | null
  _avg: ClientProjectAvgAggregateOutputType | null
  _sum: ClientProjectSumAggregateOutputType | null
  _min: ClientProjectMinAggregateOutputType | null
  _max: ClientProjectMaxAggregateOutputType | null
}

export type ClientProjectAvgAggregateOutputType = {
  budget: number | null
}

export type ClientProjectSumAggregateOutputType = {
  budget: number | null
}

export type ClientProjectMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  name: string | null
  description: string | null
  status: string | null
  budget: number | null
  currency: string | null
  startDate: Date | null
  endDate: Date | null
  deadline: Date | null
  clientAccountId: string | null
}

export type ClientProjectMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  name: string | null
  description: string | null
  status: string | null
  budget: number | null
  currency: string | null
  startDate: Date | null
  endDate: Date | null
  deadline: Date | null
  clientAccountId: string | null
}

export type ClientProjectCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  name: number
  description: number
  status: number
  budget: number
  currency: number
  startDate: number
  endDate: number
  deadline: number
  clientAccountId: number
  metadata: number
  _all: number
}


export type ClientProjectAvgAggregateInputType = {
  budget?: true
}

export type ClientProjectSumAggregateInputType = {
  budget?: true
}

export type ClientProjectMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  description?: true
  status?: true
  budget?: true
  currency?: true
  startDate?: true
  endDate?: true
  deadline?: true
  clientAccountId?: true
}

export type ClientProjectMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  description?: true
  status?: true
  budget?: true
  currency?: true
  startDate?: true
  endDate?: true
  deadline?: true
  clientAccountId?: true
}

export type ClientProjectCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  description?: true
  status?: true
  budget?: true
  currency?: true
  startDate?: true
  endDate?: true
  deadline?: true
  clientAccountId?: true
  metadata?: true
  _all?: true
}

export type ClientProjectAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClientProject to aggregate.
   */
  where?: Prisma.ClientProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientProjects to fetch.
   */
  orderBy?: Prisma.ClientProjectOrderByWithRelationInput | Prisma.ClientProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ClientProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ClientProjects
  **/
  _count?: true | ClientProjectCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ClientProjectAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ClientProjectSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ClientProjectMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ClientProjectMaxAggregateInputType
}

export type GetClientProjectAggregateType<T extends ClientProjectAggregateArgs> = {
      [P in keyof T & keyof AggregateClientProject]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClientProject[P]>
    : Prisma.GetScalarType<T[P], AggregateClientProject[P]>
}




export type ClientProjectGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClientProjectWhereInput
  orderBy?: Prisma.ClientProjectOrderByWithAggregationInput | Prisma.ClientProjectOrderByWithAggregationInput[]
  by: Prisma.ClientProjectScalarFieldEnum[] | Prisma.ClientProjectScalarFieldEnum
  having?: Prisma.ClientProjectScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ClientProjectCountAggregateInputType | true
  _avg?: ClientProjectAvgAggregateInputType
  _sum?: ClientProjectSumAggregateInputType
  _min?: ClientProjectMinAggregateInputType
  _max?: ClientProjectMaxAggregateInputType
}

export type ClientProjectGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  name: string
  description: string | null
  status: string
  budget: number | null
  currency: string
  startDate: Date | null
  endDate: Date | null
  deadline: Date | null
  clientAccountId: string
  metadata: runtime.JsonValue | null
  _count: ClientProjectCountAggregateOutputType | null
  _avg: ClientProjectAvgAggregateOutputType | null
  _sum: ClientProjectSumAggregateOutputType | null
  _min: ClientProjectMinAggregateOutputType | null
  _max: ClientProjectMaxAggregateOutputType | null
}

type GetClientProjectGroupByPayload<T extends ClientProjectGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ClientProjectGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ClientProjectGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClientProjectGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClientProjectGroupByOutputType[P]>
      }
    >
  >



export type ClientProjectWhereInput = {
  AND?: Prisma.ClientProjectWhereInput | Prisma.ClientProjectWhereInput[]
  OR?: Prisma.ClientProjectWhereInput[]
  NOT?: Prisma.ClientProjectWhereInput | Prisma.ClientProjectWhereInput[]
  id?: Prisma.StringFilter<"ClientProject"> | string
  createdAt?: Prisma.DateTimeFilter<"ClientProject"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ClientProject"> | Date | string
  name?: Prisma.StringFilter<"ClientProject"> | string
  description?: Prisma.StringNullableFilter<"ClientProject"> | string | null
  status?: Prisma.StringFilter<"ClientProject"> | string
  budget?: Prisma.FloatNullableFilter<"ClientProject"> | number | null
  currency?: Prisma.StringFilter<"ClientProject"> | string
  startDate?: Prisma.DateTimeNullableFilter<"ClientProject"> | Date | string | null
  endDate?: Prisma.DateTimeNullableFilter<"ClientProject"> | Date | string | null
  deadline?: Prisma.DateTimeNullableFilter<"ClientProject"> | Date | string | null
  clientAccountId?: Prisma.StringFilter<"ClientProject"> | string
  metadata?: Prisma.JsonNullableFilter<"ClientProject">
  Ad?: Prisma.AdListRelationFilter
  ClientAccount?: Prisma.XOR<Prisma.ClientAccountScalarRelationFilter, Prisma.ClientAccountWhereInput>
}

export type ClientProjectOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  budget?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrder
  startDate?: Prisma.SortOrderInput | Prisma.SortOrder
  endDate?: Prisma.SortOrderInput | Prisma.SortOrder
  deadline?: Prisma.SortOrderInput | Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  Ad?: Prisma.AdOrderByRelationAggregateInput
  ClientAccount?: Prisma.ClientAccountOrderByWithRelationInput
}

export type ClientProjectWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ClientProjectWhereInput | Prisma.ClientProjectWhereInput[]
  OR?: Prisma.ClientProjectWhereInput[]
  NOT?: Prisma.ClientProjectWhereInput | Prisma.ClientProjectWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"ClientProject"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ClientProject"> | Date | string
  name?: Prisma.StringFilter<"ClientProject"> | string
  description?: Prisma.StringNullableFilter<"ClientProject"> | string | null
  status?: Prisma.StringFilter<"ClientProject"> | string
  budget?: Prisma.FloatNullableFilter<"ClientProject"> | number | null
  currency?: Prisma.StringFilter<"ClientProject"> | string
  startDate?: Prisma.DateTimeNullableFilter<"ClientProject"> | Date | string | null
  endDate?: Prisma.DateTimeNullableFilter<"ClientProject"> | Date | string | null
  deadline?: Prisma.DateTimeNullableFilter<"ClientProject"> | Date | string | null
  clientAccountId?: Prisma.StringFilter<"ClientProject"> | string
  metadata?: Prisma.JsonNullableFilter<"ClientProject">
  Ad?: Prisma.AdListRelationFilter
  ClientAccount?: Prisma.XOR<Prisma.ClientAccountScalarRelationFilter, Prisma.ClientAccountWhereInput>
}, "id">

export type ClientProjectOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  budget?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrder
  startDate?: Prisma.SortOrderInput | Prisma.SortOrder
  endDate?: Prisma.SortOrderInput | Prisma.SortOrder
  deadline?: Prisma.SortOrderInput | Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ClientProjectCountOrderByAggregateInput
  _avg?: Prisma.ClientProjectAvgOrderByAggregateInput
  _max?: Prisma.ClientProjectMaxOrderByAggregateInput
  _min?: Prisma.ClientProjectMinOrderByAggregateInput
  _sum?: Prisma.ClientProjectSumOrderByAggregateInput
}

export type ClientProjectScalarWhereWithAggregatesInput = {
  AND?: Prisma.ClientProjectScalarWhereWithAggregatesInput | Prisma.ClientProjectScalarWhereWithAggregatesInput[]
  OR?: Prisma.ClientProjectScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ClientProjectScalarWhereWithAggregatesInput | Prisma.ClientProjectScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ClientProject"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ClientProject"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ClientProject"> | Date | string
  name?: Prisma.StringWithAggregatesFilter<"ClientProject"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"ClientProject"> | string | null
  status?: Prisma.StringWithAggregatesFilter<"ClientProject"> | string
  budget?: Prisma.FloatNullableWithAggregatesFilter<"ClientProject"> | number | null
  currency?: Prisma.StringWithAggregatesFilter<"ClientProject"> | string
  startDate?: Prisma.DateTimeNullableWithAggregatesFilter<"ClientProject"> | Date | string | null
  endDate?: Prisma.DateTimeNullableWithAggregatesFilter<"ClientProject"> | Date | string | null
  deadline?: Prisma.DateTimeNullableWithAggregatesFilter<"ClientProject"> | Date | string | null
  clientAccountId?: Prisma.StringWithAggregatesFilter<"ClientProject"> | string
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"ClientProject">
}

export type ClientProjectCreateInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  name: string
  description?: string | null
  status?: string
  budget?: number | null
  currency?: string
  startDate?: Date | string | null
  endDate?: Date | string | null
  deadline?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  Ad?: Prisma.AdCreateNestedManyWithoutClientProjectInput
  ClientAccount: Prisma.ClientAccountCreateNestedOneWithoutClientProjectInput
}

export type ClientProjectUncheckedCreateInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  name: string
  description?: string | null
  status?: string
  budget?: number | null
  currency?: string
  startDate?: Date | string | null
  endDate?: Date | string | null
  deadline?: Date | string | null
  clientAccountId: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  Ad?: Prisma.AdUncheckedCreateNestedManyWithoutClientProjectInput
}

export type ClientProjectUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  budget?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  Ad?: Prisma.AdUpdateManyWithoutClientProjectNestedInput
  ClientAccount?: Prisma.ClientAccountUpdateOneRequiredWithoutClientProjectNestedInput
}

export type ClientProjectUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  budget?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  clientAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  Ad?: Prisma.AdUncheckedUpdateManyWithoutClientProjectNestedInput
}

export type ClientProjectCreateManyInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  name: string
  description?: string | null
  status?: string
  budget?: number | null
  currency?: string
  startDate?: Date | string | null
  endDate?: Date | string | null
  deadline?: Date | string | null
  clientAccountId: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ClientProjectUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  budget?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ClientProjectUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  budget?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  clientAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ClientProjectNullableScalarRelationFilter = {
  is?: Prisma.ClientProjectWhereInput | null
  isNot?: Prisma.ClientProjectWhereInput | null
}

export type ClientProjectListRelationFilter = {
  every?: Prisma.ClientProjectWhereInput
  some?: Prisma.ClientProjectWhereInput
  none?: Prisma.ClientProjectWhereInput
}

export type ClientProjectOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ClientProjectCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  budget?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
}

export type ClientProjectAvgOrderByAggregateInput = {
  budget?: Prisma.SortOrder
}

export type ClientProjectMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  budget?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
}

export type ClientProjectMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  budget?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  clientAccountId?: Prisma.SortOrder
}

export type ClientProjectSumOrderByAggregateInput = {
  budget?: Prisma.SortOrder
}

export type ClientProjectCreateNestedOneWithoutAdInput = {
  create?: Prisma.XOR<Prisma.ClientProjectCreateWithoutAdInput, Prisma.ClientProjectUncheckedCreateWithoutAdInput>
  connectOrCreate?: Prisma.ClientProjectCreateOrConnectWithoutAdInput
  connect?: Prisma.ClientProjectWhereUniqueInput
}

export type ClientProjectUpdateOneWithoutAdNestedInput = {
  create?: Prisma.XOR<Prisma.ClientProjectCreateWithoutAdInput, Prisma.ClientProjectUncheckedCreateWithoutAdInput>
  connectOrCreate?: Prisma.ClientProjectCreateOrConnectWithoutAdInput
  upsert?: Prisma.ClientProjectUpsertWithoutAdInput
  disconnect?: Prisma.ClientProjectWhereInput | boolean
  delete?: Prisma.ClientProjectWhereInput | boolean
  connect?: Prisma.ClientProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClientProjectUpdateToOneWithWhereWithoutAdInput, Prisma.ClientProjectUpdateWithoutAdInput>, Prisma.ClientProjectUncheckedUpdateWithoutAdInput>
}

export type ClientProjectCreateNestedManyWithoutClientAccountInput = {
  create?: Prisma.XOR<Prisma.ClientProjectCreateWithoutClientAccountInput, Prisma.ClientProjectUncheckedCreateWithoutClientAccountInput> | Prisma.ClientProjectCreateWithoutClientAccountInput[] | Prisma.ClientProjectUncheckedCreateWithoutClientAccountInput[]
  connectOrCreate?: Prisma.ClientProjectCreateOrConnectWithoutClientAccountInput | Prisma.ClientProjectCreateOrConnectWithoutClientAccountInput[]
  createMany?: Prisma.ClientProjectCreateManyClientAccountInputEnvelope
  connect?: Prisma.ClientProjectWhereUniqueInput | Prisma.ClientProjectWhereUniqueInput[]
}

export type ClientProjectUncheckedCreateNestedManyWithoutClientAccountInput = {
  create?: Prisma.XOR<Prisma.ClientProjectCreateWithoutClientAccountInput, Prisma.ClientProjectUncheckedCreateWithoutClientAccountInput> | Prisma.ClientProjectCreateWithoutClientAccountInput[] | Prisma.ClientProjectUncheckedCreateWithoutClientAccountInput[]
  connectOrCreate?: Prisma.ClientProjectCreateOrConnectWithoutClientAccountInput | Prisma.ClientProjectCreateOrConnectWithoutClientAccountInput[]
  createMany?: Prisma.ClientProjectCreateManyClientAccountInputEnvelope
  connect?: Prisma.ClientProjectWhereUniqueInput | Prisma.ClientProjectWhereUniqueInput[]
}

export type ClientProjectUpdateManyWithoutClientAccountNestedInput = {
  create?: Prisma.XOR<Prisma.ClientProjectCreateWithoutClientAccountInput, Prisma.ClientProjectUncheckedCreateWithoutClientAccountInput> | Prisma.ClientProjectCreateWithoutClientAccountInput[] | Prisma.ClientProjectUncheckedCreateWithoutClientAccountInput[]
  connectOrCreate?: Prisma.ClientProjectCreateOrConnectWithoutClientAccountInput | Prisma.ClientProjectCreateOrConnectWithoutClientAccountInput[]
  upsert?: Prisma.ClientProjectUpsertWithWhereUniqueWithoutClientAccountInput | Prisma.ClientProjectUpsertWithWhereUniqueWithoutClientAccountInput[]
  createMany?: Prisma.ClientProjectCreateManyClientAccountInputEnvelope
  set?: Prisma.ClientProjectWhereUniqueInput | Prisma.ClientProjectWhereUniqueInput[]
  disconnect?: Prisma.ClientProjectWhereUniqueInput | Prisma.ClientProjectWhereUniqueInput[]
  delete?: Prisma.ClientProjectWhereUniqueInput | Prisma.ClientProjectWhereUniqueInput[]
  connect?: Prisma.ClientProjectWhereUniqueInput | Prisma.ClientProjectWhereUniqueInput[]
  update?: Prisma.ClientProjectUpdateWithWhereUniqueWithoutClientAccountInput | Prisma.ClientProjectUpdateWithWhereUniqueWithoutClientAccountInput[]
  updateMany?: Prisma.ClientProjectUpdateManyWithWhereWithoutClientAccountInput | Prisma.ClientProjectUpdateManyWithWhereWithoutClientAccountInput[]
  deleteMany?: Prisma.ClientProjectScalarWhereInput | Prisma.ClientProjectScalarWhereInput[]
}

export type ClientProjectUncheckedUpdateManyWithoutClientAccountNestedInput = {
  create?: Prisma.XOR<Prisma.ClientProjectCreateWithoutClientAccountInput, Prisma.ClientProjectUncheckedCreateWithoutClientAccountInput> | Prisma.ClientProjectCreateWithoutClientAccountInput[] | Prisma.ClientProjectUncheckedCreateWithoutClientAccountInput[]
  connectOrCreate?: Prisma.ClientProjectCreateOrConnectWithoutClientAccountInput | Prisma.ClientProjectCreateOrConnectWithoutClientAccountInput[]
  upsert?: Prisma.ClientProjectUpsertWithWhereUniqueWithoutClientAccountInput | Prisma.ClientProjectUpsertWithWhereUniqueWithoutClientAccountInput[]
  createMany?: Prisma.ClientProjectCreateManyClientAccountInputEnvelope
  set?: Prisma.ClientProjectWhereUniqueInput | Prisma.ClientProjectWhereUniqueInput[]
  disconnect?: Prisma.ClientProjectWhereUniqueInput | Prisma.ClientProjectWhereUniqueInput[]
  delete?: Prisma.ClientProjectWhereUniqueInput | Prisma.ClientProjectWhereUniqueInput[]
  connect?: Prisma.ClientProjectWhereUniqueInput | Prisma.ClientProjectWhereUniqueInput[]
  update?: Prisma.ClientProjectUpdateWithWhereUniqueWithoutClientAccountInput | Prisma.ClientProjectUpdateWithWhereUniqueWithoutClientAccountInput[]
  updateMany?: Prisma.ClientProjectUpdateManyWithWhereWithoutClientAccountInput | Prisma.ClientProjectUpdateManyWithWhereWithoutClientAccountInput[]
  deleteMany?: Prisma.ClientProjectScalarWhereInput | Prisma.ClientProjectScalarWhereInput[]
}

export type ClientProjectCreateWithoutAdInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  name: string
  description?: string | null
  status?: string
  budget?: number | null
  currency?: string
  startDate?: Date | string | null
  endDate?: Date | string | null
  deadline?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  ClientAccount: Prisma.ClientAccountCreateNestedOneWithoutClientProjectInput
}

export type ClientProjectUncheckedCreateWithoutAdInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  name: string
  description?: string | null
  status?: string
  budget?: number | null
  currency?: string
  startDate?: Date | string | null
  endDate?: Date | string | null
  deadline?: Date | string | null
  clientAccountId: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ClientProjectCreateOrConnectWithoutAdInput = {
  where: Prisma.ClientProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ClientProjectCreateWithoutAdInput, Prisma.ClientProjectUncheckedCreateWithoutAdInput>
}

export type ClientProjectUpsertWithoutAdInput = {
  update: Prisma.XOR<Prisma.ClientProjectUpdateWithoutAdInput, Prisma.ClientProjectUncheckedUpdateWithoutAdInput>
  create: Prisma.XOR<Prisma.ClientProjectCreateWithoutAdInput, Prisma.ClientProjectUncheckedCreateWithoutAdInput>
  where?: Prisma.ClientProjectWhereInput
}

export type ClientProjectUpdateToOneWithWhereWithoutAdInput = {
  where?: Prisma.ClientProjectWhereInput
  data: Prisma.XOR<Prisma.ClientProjectUpdateWithoutAdInput, Prisma.ClientProjectUncheckedUpdateWithoutAdInput>
}

export type ClientProjectUpdateWithoutAdInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  budget?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  ClientAccount?: Prisma.ClientAccountUpdateOneRequiredWithoutClientProjectNestedInput
}

export type ClientProjectUncheckedUpdateWithoutAdInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  budget?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  clientAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ClientProjectCreateWithoutClientAccountInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  name: string
  description?: string | null
  status?: string
  budget?: number | null
  currency?: string
  startDate?: Date | string | null
  endDate?: Date | string | null
  deadline?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  Ad?: Prisma.AdCreateNestedManyWithoutClientProjectInput
}

export type ClientProjectUncheckedCreateWithoutClientAccountInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  name: string
  description?: string | null
  status?: string
  budget?: number | null
  currency?: string
  startDate?: Date | string | null
  endDate?: Date | string | null
  deadline?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  Ad?: Prisma.AdUncheckedCreateNestedManyWithoutClientProjectInput
}

export type ClientProjectCreateOrConnectWithoutClientAccountInput = {
  where: Prisma.ClientProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ClientProjectCreateWithoutClientAccountInput, Prisma.ClientProjectUncheckedCreateWithoutClientAccountInput>
}

export type ClientProjectCreateManyClientAccountInputEnvelope = {
  data: Prisma.ClientProjectCreateManyClientAccountInput | Prisma.ClientProjectCreateManyClientAccountInput[]
  skipDuplicates?: boolean
}

export type ClientProjectUpsertWithWhereUniqueWithoutClientAccountInput = {
  where: Prisma.ClientProjectWhereUniqueInput
  update: Prisma.XOR<Prisma.ClientProjectUpdateWithoutClientAccountInput, Prisma.ClientProjectUncheckedUpdateWithoutClientAccountInput>
  create: Prisma.XOR<Prisma.ClientProjectCreateWithoutClientAccountInput, Prisma.ClientProjectUncheckedCreateWithoutClientAccountInput>
}

export type ClientProjectUpdateWithWhereUniqueWithoutClientAccountInput = {
  where: Prisma.ClientProjectWhereUniqueInput
  data: Prisma.XOR<Prisma.ClientProjectUpdateWithoutClientAccountInput, Prisma.ClientProjectUncheckedUpdateWithoutClientAccountInput>
}

export type ClientProjectUpdateManyWithWhereWithoutClientAccountInput = {
  where: Prisma.ClientProjectScalarWhereInput
  data: Prisma.XOR<Prisma.ClientProjectUpdateManyMutationInput, Prisma.ClientProjectUncheckedUpdateManyWithoutClientAccountInput>
}

export type ClientProjectScalarWhereInput = {
  AND?: Prisma.ClientProjectScalarWhereInput | Prisma.ClientProjectScalarWhereInput[]
  OR?: Prisma.ClientProjectScalarWhereInput[]
  NOT?: Prisma.ClientProjectScalarWhereInput | Prisma.ClientProjectScalarWhereInput[]
  id?: Prisma.StringFilter<"ClientProject"> | string
  createdAt?: Prisma.DateTimeFilter<"ClientProject"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ClientProject"> | Date | string
  name?: Prisma.StringFilter<"ClientProject"> | string
  description?: Prisma.StringNullableFilter<"ClientProject"> | string | null
  status?: Prisma.StringFilter<"ClientProject"> | string
  budget?: Prisma.FloatNullableFilter<"ClientProject"> | number | null
  currency?: Prisma.StringFilter<"ClientProject"> | string
  startDate?: Prisma.DateTimeNullableFilter<"ClientProject"> | Date | string | null
  endDate?: Prisma.DateTimeNullableFilter<"ClientProject"> | Date | string | null
  deadline?: Prisma.DateTimeNullableFilter<"ClientProject"> | Date | string | null
  clientAccountId?: Prisma.StringFilter<"ClientProject"> | string
  metadata?: Prisma.JsonNullableFilter<"ClientProject">
}

export type ClientProjectCreateManyClientAccountInput = {
  id: string
  createdAt?: Date | string
  updatedAt: Date | string
  name: string
  description?: string | null
  status?: string
  budget?: number | null
  currency?: string
  startDate?: Date | string | null
  endDate?: Date | string | null
  deadline?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ClientProjectUpdateWithoutClientAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  budget?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  Ad?: Prisma.AdUpdateManyWithoutClientProjectNestedInput
}

export type ClientProjectUncheckedUpdateWithoutClientAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  budget?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  Ad?: Prisma.AdUncheckedUpdateManyWithoutClientProjectNestedInput
}

export type ClientProjectUncheckedUpdateManyWithoutClientAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  budget?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}


/**
 * Count Type ClientProjectCountOutputType
 */

export type ClientProjectCountOutputType = {
  Ad: number
}

export type ClientProjectCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Ad?: boolean | ClientProjectCountOutputTypeCountAdArgs
}

/**
 * ClientProjectCountOutputType without action
 */
export type ClientProjectCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientProjectCountOutputType
   */
  select?: Prisma.ClientProjectCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ClientProjectCountOutputType without action
 */
export type ClientProjectCountOutputTypeCountAdArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AdWhereInput
}


export type ClientProjectSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  description?: boolean
  status?: boolean
  budget?: boolean
  currency?: boolean
  startDate?: boolean
  endDate?: boolean
  deadline?: boolean
  clientAccountId?: boolean
  metadata?: boolean
  Ad?: boolean | Prisma.ClientProject$AdArgs<ExtArgs>
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.ClientProjectCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clientProject"]>

export type ClientProjectSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  description?: boolean
  status?: boolean
  budget?: boolean
  currency?: boolean
  startDate?: boolean
  endDate?: boolean
  deadline?: boolean
  clientAccountId?: boolean
  metadata?: boolean
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clientProject"]>

export type ClientProjectSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  description?: boolean
  status?: boolean
  budget?: boolean
  currency?: boolean
  startDate?: boolean
  endDate?: boolean
  deadline?: boolean
  clientAccountId?: boolean
  metadata?: boolean
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clientProject"]>

export type ClientProjectSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  description?: boolean
  status?: boolean
  budget?: boolean
  currency?: boolean
  startDate?: boolean
  endDate?: boolean
  deadline?: boolean
  clientAccountId?: boolean
  metadata?: boolean
}

export type ClientProjectOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "name" | "description" | "status" | "budget" | "currency" | "startDate" | "endDate" | "deadline" | "clientAccountId" | "metadata", ExtArgs["result"]["clientProject"]>
export type ClientProjectInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Ad?: boolean | Prisma.ClientProject$AdArgs<ExtArgs>
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.ClientProjectCountOutputTypeDefaultArgs<ExtArgs>
}
export type ClientProjectIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}
export type ClientProjectIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ClientAccount?: boolean | Prisma.ClientAccountDefaultArgs<ExtArgs>
}

export type $ClientProjectPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ClientProject"
  objects: {
    Ad: Prisma.$AdPayload<ExtArgs>[]
    ClientAccount: Prisma.$ClientAccountPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    name: string
    description: string | null
    status: string
    budget: number | null
    currency: string
    startDate: Date | null
    endDate: Date | null
    deadline: Date | null
    clientAccountId: string
    metadata: runtime.JsonValue | null
  }, ExtArgs["result"]["clientProject"]>
  composites: {}
}

export type ClientProjectGetPayload<S extends boolean | null | undefined | ClientProjectDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ClientProjectPayload, S>

export type ClientProjectCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ClientProjectFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ClientProjectCountAggregateInputType | true
  }

export interface ClientProjectDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ClientProject'], meta: { name: 'ClientProject' } }
  /**
   * Find zero or one ClientProject that matches the filter.
   * @param {ClientProjectFindUniqueArgs} args - Arguments to find a ClientProject
   * @example
   * // Get one ClientProject
   * const clientProject = await prisma.clientProject.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClientProjectFindUniqueArgs>(args: Prisma.SelectSubset<T, ClientProjectFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ClientProjectClient<runtime.Types.Result.GetResult<Prisma.$ClientProjectPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ClientProject that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClientProjectFindUniqueOrThrowArgs} args - Arguments to find a ClientProject
   * @example
   * // Get one ClientProject
   * const clientProject = await prisma.clientProject.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClientProjectFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ClientProjectFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClientProjectClient<runtime.Types.Result.GetResult<Prisma.$ClientProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClientProject that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientProjectFindFirstArgs} args - Arguments to find a ClientProject
   * @example
   * // Get one ClientProject
   * const clientProject = await prisma.clientProject.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClientProjectFindFirstArgs>(args?: Prisma.SelectSubset<T, ClientProjectFindFirstArgs<ExtArgs>>): Prisma.Prisma__ClientProjectClient<runtime.Types.Result.GetResult<Prisma.$ClientProjectPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClientProject that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientProjectFindFirstOrThrowArgs} args - Arguments to find a ClientProject
   * @example
   * // Get one ClientProject
   * const clientProject = await prisma.clientProject.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClientProjectFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ClientProjectFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClientProjectClient<runtime.Types.Result.GetResult<Prisma.$ClientProjectPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ClientProjects that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientProjectFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ClientProjects
   * const clientProjects = await prisma.clientProject.findMany()
   * 
   * // Get first 10 ClientProjects
   * const clientProjects = await prisma.clientProject.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const clientProjectWithIdOnly = await prisma.clientProject.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ClientProjectFindManyArgs>(args?: Prisma.SelectSubset<T, ClientProjectFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ClientProject.
   * @param {ClientProjectCreateArgs} args - Arguments to create a ClientProject.
   * @example
   * // Create one ClientProject
   * const ClientProject = await prisma.clientProject.create({
   *   data: {
   *     // ... data to create a ClientProject
   *   }
   * })
   * 
   */
  create<T extends ClientProjectCreateArgs>(args: Prisma.SelectSubset<T, ClientProjectCreateArgs<ExtArgs>>): Prisma.Prisma__ClientProjectClient<runtime.Types.Result.GetResult<Prisma.$ClientProjectPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ClientProjects.
   * @param {ClientProjectCreateManyArgs} args - Arguments to create many ClientProjects.
   * @example
   * // Create many ClientProjects
   * const clientProject = await prisma.clientProject.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ClientProjectCreateManyArgs>(args?: Prisma.SelectSubset<T, ClientProjectCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ClientProjects and returns the data saved in the database.
   * @param {ClientProjectCreateManyAndReturnArgs} args - Arguments to create many ClientProjects.
   * @example
   * // Create many ClientProjects
   * const clientProject = await prisma.clientProject.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ClientProjects and only return the `id`
   * const clientProjectWithIdOnly = await prisma.clientProject.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ClientProjectCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ClientProjectCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientProjectPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ClientProject.
   * @param {ClientProjectDeleteArgs} args - Arguments to delete one ClientProject.
   * @example
   * // Delete one ClientProject
   * const ClientProject = await prisma.clientProject.delete({
   *   where: {
   *     // ... filter to delete one ClientProject
   *   }
   * })
   * 
   */
  delete<T extends ClientProjectDeleteArgs>(args: Prisma.SelectSubset<T, ClientProjectDeleteArgs<ExtArgs>>): Prisma.Prisma__ClientProjectClient<runtime.Types.Result.GetResult<Prisma.$ClientProjectPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ClientProject.
   * @param {ClientProjectUpdateArgs} args - Arguments to update one ClientProject.
   * @example
   * // Update one ClientProject
   * const clientProject = await prisma.clientProject.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ClientProjectUpdateArgs>(args: Prisma.SelectSubset<T, ClientProjectUpdateArgs<ExtArgs>>): Prisma.Prisma__ClientProjectClient<runtime.Types.Result.GetResult<Prisma.$ClientProjectPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ClientProjects.
   * @param {ClientProjectDeleteManyArgs} args - Arguments to filter ClientProjects to delete.
   * @example
   * // Delete a few ClientProjects
   * const { count } = await prisma.clientProject.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ClientProjectDeleteManyArgs>(args?: Prisma.SelectSubset<T, ClientProjectDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ClientProjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientProjectUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ClientProjects
   * const clientProject = await prisma.clientProject.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ClientProjectUpdateManyArgs>(args: Prisma.SelectSubset<T, ClientProjectUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ClientProjects and returns the data updated in the database.
   * @param {ClientProjectUpdateManyAndReturnArgs} args - Arguments to update many ClientProjects.
   * @example
   * // Update many ClientProjects
   * const clientProject = await prisma.clientProject.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ClientProjects and only return the `id`
   * const clientProjectWithIdOnly = await prisma.clientProject.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ClientProjectUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ClientProjectUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientProjectPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ClientProject.
   * @param {ClientProjectUpsertArgs} args - Arguments to update or create a ClientProject.
   * @example
   * // Update or create a ClientProject
   * const clientProject = await prisma.clientProject.upsert({
   *   create: {
   *     // ... data to create a ClientProject
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ClientProject we want to update
   *   }
   * })
   */
  upsert<T extends ClientProjectUpsertArgs>(args: Prisma.SelectSubset<T, ClientProjectUpsertArgs<ExtArgs>>): Prisma.Prisma__ClientProjectClient<runtime.Types.Result.GetResult<Prisma.$ClientProjectPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ClientProjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientProjectCountArgs} args - Arguments to filter ClientProjects to count.
   * @example
   * // Count the number of ClientProjects
   * const count = await prisma.clientProject.count({
   *   where: {
   *     // ... the filter for the ClientProjects we want to count
   *   }
   * })
  **/
  count<T extends ClientProjectCountArgs>(
    args?: Prisma.Subset<T, ClientProjectCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClientProjectCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ClientProject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientProjectAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ClientProjectAggregateArgs>(args: Prisma.Subset<T, ClientProjectAggregateArgs>): Prisma.PrismaPromise<GetClientProjectAggregateType<T>>

  /**
   * Group by ClientProject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientProjectGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ClientProjectGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ClientProjectGroupByArgs['orderBy'] }
      : { orderBy?: ClientProjectGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ClientProjectGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClientProjectGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ClientProject model
 */
readonly fields: ClientProjectFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ClientProject.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClientProjectClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Ad<T extends Prisma.ClientProject$AdArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClientProject$AdArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  ClientAccount<T extends Prisma.ClientAccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClientAccountDefaultArgs<ExtArgs>>): Prisma.Prisma__ClientAccountClient<runtime.Types.Result.GetResult<Prisma.$ClientAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ClientProject model
 */
export interface ClientProjectFieldRefs {
  readonly id: Prisma.FieldRef<"ClientProject", 'String'>
  readonly createdAt: Prisma.FieldRef<"ClientProject", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ClientProject", 'DateTime'>
  readonly name: Prisma.FieldRef<"ClientProject", 'String'>
  readonly description: Prisma.FieldRef<"ClientProject", 'String'>
  readonly status: Prisma.FieldRef<"ClientProject", 'String'>
  readonly budget: Prisma.FieldRef<"ClientProject", 'Float'>
  readonly currency: Prisma.FieldRef<"ClientProject", 'String'>
  readonly startDate: Prisma.FieldRef<"ClientProject", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"ClientProject", 'DateTime'>
  readonly deadline: Prisma.FieldRef<"ClientProject", 'DateTime'>
  readonly clientAccountId: Prisma.FieldRef<"ClientProject", 'String'>
  readonly metadata: Prisma.FieldRef<"ClientProject", 'Json'>
}
    

// Custom InputTypes
/**
 * ClientProject findUnique
 */
export type ClientProjectFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientProject
   */
  select?: Prisma.ClientProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientProject
   */
  omit?: Prisma.ClientProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientProjectInclude<ExtArgs> | null
  /**
   * Filter, which ClientProject to fetch.
   */
  where: Prisma.ClientProjectWhereUniqueInput
}

/**
 * ClientProject findUniqueOrThrow
 */
export type ClientProjectFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientProject
   */
  select?: Prisma.ClientProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientProject
   */
  omit?: Prisma.ClientProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientProjectInclude<ExtArgs> | null
  /**
   * Filter, which ClientProject to fetch.
   */
  where: Prisma.ClientProjectWhereUniqueInput
}

/**
 * ClientProject findFirst
 */
export type ClientProjectFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientProject
   */
  select?: Prisma.ClientProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientProject
   */
  omit?: Prisma.ClientProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientProjectInclude<ExtArgs> | null
  /**
   * Filter, which ClientProject to fetch.
   */
  where?: Prisma.ClientProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientProjects to fetch.
   */
  orderBy?: Prisma.ClientProjectOrderByWithRelationInput | Prisma.ClientProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClientProjects.
   */
  cursor?: Prisma.ClientProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClientProjects.
   */
  distinct?: Prisma.ClientProjectScalarFieldEnum | Prisma.ClientProjectScalarFieldEnum[]
}

/**
 * ClientProject findFirstOrThrow
 */
export type ClientProjectFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientProject
   */
  select?: Prisma.ClientProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientProject
   */
  omit?: Prisma.ClientProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientProjectInclude<ExtArgs> | null
  /**
   * Filter, which ClientProject to fetch.
   */
  where?: Prisma.ClientProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientProjects to fetch.
   */
  orderBy?: Prisma.ClientProjectOrderByWithRelationInput | Prisma.ClientProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClientProjects.
   */
  cursor?: Prisma.ClientProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClientProjects.
   */
  distinct?: Prisma.ClientProjectScalarFieldEnum | Prisma.ClientProjectScalarFieldEnum[]
}

/**
 * ClientProject findMany
 */
export type ClientProjectFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientProject
   */
  select?: Prisma.ClientProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientProject
   */
  omit?: Prisma.ClientProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientProjectInclude<ExtArgs> | null
  /**
   * Filter, which ClientProjects to fetch.
   */
  where?: Prisma.ClientProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClientProjects to fetch.
   */
  orderBy?: Prisma.ClientProjectOrderByWithRelationInput | Prisma.ClientProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ClientProjects.
   */
  cursor?: Prisma.ClientProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClientProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClientProjects.
   */
  skip?: number
  distinct?: Prisma.ClientProjectScalarFieldEnum | Prisma.ClientProjectScalarFieldEnum[]
}

/**
 * ClientProject create
 */
export type ClientProjectCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientProject
   */
  select?: Prisma.ClientProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientProject
   */
  omit?: Prisma.ClientProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientProjectInclude<ExtArgs> | null
  /**
   * The data needed to create a ClientProject.
   */
  data: Prisma.XOR<Prisma.ClientProjectCreateInput, Prisma.ClientProjectUncheckedCreateInput>
}

/**
 * ClientProject createMany
 */
export type ClientProjectCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ClientProjects.
   */
  data: Prisma.ClientProjectCreateManyInput | Prisma.ClientProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ClientProject createManyAndReturn
 */
export type ClientProjectCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientProject
   */
  select?: Prisma.ClientProjectSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ClientProject
   */
  omit?: Prisma.ClientProjectOmit<ExtArgs> | null
  /**
   * The data used to create many ClientProjects.
   */
  data: Prisma.ClientProjectCreateManyInput | Prisma.ClientProjectCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientProjectIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ClientProject update
 */
export type ClientProjectUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientProject
   */
  select?: Prisma.ClientProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientProject
   */
  omit?: Prisma.ClientProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientProjectInclude<ExtArgs> | null
  /**
   * The data needed to update a ClientProject.
   */
  data: Prisma.XOR<Prisma.ClientProjectUpdateInput, Prisma.ClientProjectUncheckedUpdateInput>
  /**
   * Choose, which ClientProject to update.
   */
  where: Prisma.ClientProjectWhereUniqueInput
}

/**
 * ClientProject updateMany
 */
export type ClientProjectUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ClientProjects.
   */
  data: Prisma.XOR<Prisma.ClientProjectUpdateManyMutationInput, Prisma.ClientProjectUncheckedUpdateManyInput>
  /**
   * Filter which ClientProjects to update
   */
  where?: Prisma.ClientProjectWhereInput
  /**
   * Limit how many ClientProjects to update.
   */
  limit?: number
}

/**
 * ClientProject updateManyAndReturn
 */
export type ClientProjectUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientProject
   */
  select?: Prisma.ClientProjectSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ClientProject
   */
  omit?: Prisma.ClientProjectOmit<ExtArgs> | null
  /**
   * The data used to update ClientProjects.
   */
  data: Prisma.XOR<Prisma.ClientProjectUpdateManyMutationInput, Prisma.ClientProjectUncheckedUpdateManyInput>
  /**
   * Filter which ClientProjects to update
   */
  where?: Prisma.ClientProjectWhereInput
  /**
   * Limit how many ClientProjects to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientProjectIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ClientProject upsert
 */
export type ClientProjectUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientProject
   */
  select?: Prisma.ClientProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientProject
   */
  omit?: Prisma.ClientProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientProjectInclude<ExtArgs> | null
  /**
   * The filter to search for the ClientProject to update in case it exists.
   */
  where: Prisma.ClientProjectWhereUniqueInput
  /**
   * In case the ClientProject found by the `where` argument doesn't exist, create a new ClientProject with this data.
   */
  create: Prisma.XOR<Prisma.ClientProjectCreateInput, Prisma.ClientProjectUncheckedCreateInput>
  /**
   * In case the ClientProject was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClientProjectUpdateInput, Prisma.ClientProjectUncheckedUpdateInput>
}

/**
 * ClientProject delete
 */
export type ClientProjectDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientProject
   */
  select?: Prisma.ClientProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientProject
   */
  omit?: Prisma.ClientProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientProjectInclude<ExtArgs> | null
  /**
   * Filter which ClientProject to delete.
   */
  where: Prisma.ClientProjectWhereUniqueInput
}

/**
 * ClientProject deleteMany
 */
export type ClientProjectDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClientProjects to delete
   */
  where?: Prisma.ClientProjectWhereInput
  /**
   * Limit how many ClientProjects to delete.
   */
  limit?: number
}

/**
 * ClientProject.Ad
 */
export type ClientProject$AdArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ad
   */
  select?: Prisma.AdSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ad
   */
  omit?: Prisma.AdOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdInclude<ExtArgs> | null
  where?: Prisma.AdWhereInput
  orderBy?: Prisma.AdOrderByWithRelationInput | Prisma.AdOrderByWithRelationInput[]
  cursor?: Prisma.AdWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AdScalarFieldEnum | Prisma.AdScalarFieldEnum[]
}

/**
 * ClientProject without action
 */
export type ClientProjectDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientProject
   */
  select?: Prisma.ClientProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClientProject
   */
  omit?: Prisma.ClientProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientProjectInclude<ExtArgs> | null
}
